project_name: protoc-gen-apigw
builds:
  - binary: protoc-gen-apigw
    env:
      - CGO_ENABLED=0
    id: linux
    main: .
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/ductone/protoc-gen-apigw:{{ .Version }}-amd64"
      - "ghcr.io/ductone/protoc-gen-apigw:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/ductone/protoc-gen-apigw:{{ .Version }}-arm64"
      - "ghcr.io/ductone/protoc-gen-apigw:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghcr.io/ductone/protoc-gen-apigw:{{ .Version }}
    image_templates:
      - ghcr.io/ductone/protoc-gen-apigw:{{ .Version }}-amd64
      - ghcr.io/ductone/protoc-gen-apigw:{{ .Version }}-arm64
  - name_template: ghcr.io/ductone/protoc-gen-apigw:latest
    image_templates:
      - ghcr.io/ductone/protoc-gen-apigw:latest-amd64
      - ghcr.io/ductone/protoc-gen-apigw:latest-arm64
checksum:
  disable: true
release:
  disable: true
changelog:
  skip: true