---
components:
  schemas:
    bookstore.v1.Author:
      description: |2
         An author resource.
      properties:
        firstName:
          type: string
        gender:
          description: The gender field.
          enum:
            - GENDER_UNSPECIFIED
            - GENDER_MALE
            - GENDER_FEMALE
          type: string
        id:
          format: int64
          type: string
        lname:
          type: string
      type: object
    bookstore.v1.Book:
      description: |2
         A book resource.
      properties:
        author:
          type: string
        id:
          format: int64
          type: string
        quotes:
          description: |2
             Quotes from the book.
          items:
            type: string
          nullable: true
          type: array
        title:
          type: string
      type: object
    bookstore.v1.CreateBookRequestInput:
      description: |2
         Request message for CreateBook method.
      properties:
        book:
          $ref: '#/components/schemas/bookstore.v1.Book'
      type: object
    bookstore.v1.CreateBookResponse:
      description: The CreateBookResponse message.
      properties:
        book:
          $ref: '#/components/schemas/bookstore.v1.Book'
      type: object
    bookstore.v1.CreateShelfRequest:
      description: |2
         Request message for CreateShelf method.
      properties:
        shelf:
          $ref: '#/components/schemas/bookstore.v1.Shelf'
      type: object
    bookstore.v1.CreateShelfResponse:
      description: The CreateShelfResponse message.
      properties:
        shelf:
          $ref: '#/components/schemas/bookstore.v1.Shelf'
      type: object
    bookstore.v1.DeleteBookRequestInput:
      description: |2
         Request message for DeleteBook method.
      type: object
    bookstore.v1.DeleteBookResponse:
      description: The DeleteBookResponse message.
      type: object
    bookstore.v1.DeleteShelfRequestInput:
      description: |2
         Request message for DeleteShelf method.
      type: object
    bookstore.v1.DeleteShelfResponse:
      description: The DeleteShelfResponse message.
      type: object
    bookstore.v1.GetAuthorResponse:
      description: The GetAuthorResponse message.
      properties:
        author:
          $ref: '#/components/schemas/bookstore.v1.Author'
      type: object
    bookstore.v1.GetBookResponse:
      description: The GetBookResponse message.
      properties:
        book:
          $ref: '#/components/schemas/bookstore.v1.Book'
      type: object
    bookstore.v1.ListShelvesResponse:
      description: |2
         Response to ListShelves call.
      properties:
        shelves:
          description: |2
             Shelves in the bookstore.
          items:
            $ref: '#/components/schemas/bookstore.v1.Shelf'
          nullable: true
          type: array
      type: object
    bookstore.v1.Shelf:
      description: |2
         A shelf resource.
      properties:
        id:
          format: int64
          type: string
        search%5Bencoded%5D:
          type: string
        search[decoded]:
          type: string
        theme:
          type: string
      type: object
    bookstore.v1.UpdateBookRequestInput:
      description: |2
         Request message for UpdateBook method
      properties:
        book:
          $ref: '#/components/schemas/bookstore.v1.Book'
      type: object
    bookstore.v1.UpdateBookResponse:
      description: The UpdateBookResponse message.
      properties:
        book:
          $ref: '#/components/schemas/bookstore.v1.Book'
      type: object
info:
  description: |
    This is an auto-generated API for bookstore.v1.BookstoreService.
  title: API For bookstore.v1.BookstoreService
  version: 0.0.1
openapi: 3.1.0
paths:
  /authors/{author}:
    get:
      description: |2
         Returns a specific author.
      operationId: bookstore.v1.BookstoreService.GetAuthor
      parameters:
        - in: path
          name: author
          required: true
          schema:
            format: int64
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.GetAuthorResponse'
          description: Succesful response
  /shelf:
    post:
      description: |2
         Creates a new shelf in the bookstore.
      operationId: bookstore.v1.BookstoreService.CreateShelf
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bookstore.v1.CreateShelfRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.CreateShelfResponse'
          description: Succesful response
  /shelves:
    get:
      description: |2
         Returns a list of all shelves in the bookstore.
      operationId: bookstore.v1.BookstoreService.ListShelves
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.ListShelvesResponse'
          description: |2
             Response to ListShelves call.
  /shelves/{shelf}:
    delete:
      description: |2
         Deletes a shelf, including all books that are stored on the shelf.
      operationId: bookstore.v1.BookstoreService.DeleteShelf
      parameters:
        - in: path
          name: shelf
          required: true
          schema:
            format: int64
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bookstore.v1.DeleteShelfRequestInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.DeleteShelfResponse'
          description: Succesful response
  /shelves/{shelf}/books:
    post:
      description: |2
         Creates a new book.
      operationId: bookstore.v1.BookstoreService.CreateBook
      parameters:
        - in: path
          name: shelf
          required: true
          schema:
            format: int64
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bookstore.v1.CreateBookRequestInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.CreateBookResponse'
          description: Succesful response
  /shelves/{shelf}/books/{book.id}:
    patch:
      description: Invokes the bookstore.v1.BookstoreService.UpdateBook method.
      operationId: bookstore.v1.BookstoreService.UpdateBook
      parameters:
        - in: path
          name: shelf
          required: true
          schema:
            format: int64
            type: string
        - in: path
          name: book.id
          required: true
          schema:
            format: int64
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bookstore.v1.UpdateBookRequestInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.UpdateBookResponse'
          description: Succesful response
  /shelves/{shelf}/books/{book}:
    delete:
      description: |2
         Deletes a book from a shelf.
      operationId: bookstore.v1.BookstoreService.DeleteBook
      parameters:
        - in: path
          name: shelf
          required: true
          schema:
            format: int64
            type: string
        - in: path
          name: book
          required: true
          schema:
            format: int64
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bookstore.v1.DeleteBookRequestInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.DeleteBookResponse'
          description: Succesful response
    get:
      description: |2
         Returns a specific book.
      operationId: bookstore.v1.BookstoreService.GetBook
      parameters:
        - in: path
          name: shelf
          required: true
          schema:
            format: int64
            type: string
        - in: path
          name: book
          required: true
          schema:
            format: int64
            type: string
        - in: query
          name: author
          schema:
            type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.GetBookResponse'
          description: Succesful response
servers:
  - description: The server for bookstore.v1.BookstoreService.
    url: /
