---
components:
  schemas:
    bookstore.v1.Author:
      description: |2
         An author resource.
      properties:
        firstName:
          description: The firstName field.
          type: string
        gender:
          description: The gender field.
          enum:
            - GENDER_UNSPECIFIED
            - GENDER_MALE
            - GENDER_FEMALE
          type: string
        id:
          description: |2
             A unique author id.
          format: int64
          type: string
        lname:
          description: The lname field.
          type: string
      type: object
      x-speakeasy-name-override: Author
    bookstore.v1.Book:
      description: |2
         A book resource.
      properties:
        author:
          description: |2
             An author of the book.
          type: string
        id:
          description: |2
             A unique book id.
          format: int64
          type: string
        quotes:
          description: |2
             Quotes from the book.
          items:
            type: string
          nullable: true
          type: array
        title:
          description: |2
             A book title.
          type: string
      required:
        - id
      type: object
      x-speakeasy-entity: Book
      x-speakeasy-name-override: Book
    bookstore.v1.CreateBookRequestInput:
      description: |2
         Request message for CreateBook method.
      properties:
        book:
          $ref: '#/components/schemas/bookstore.v1.Book'
      type: object
      x-speakeasy-name-override: CreateBookRequest
    bookstore.v1.CreateBookResponse:
      description: The CreateBookResponse message.
      properties:
        book:
          $ref: '#/components/schemas/bookstore.v1.Book'
      type: object
      x-speakeasy-name-override: CreateBookResponse
    bookstore.v1.CreateShelfRequest:
      description: |2
         Request message for CreateShelf method.
      properties:
        shelf:
          $ref: '#/components/schemas/bookstore.v1.Shelf'
      type: object
      x-speakeasy-name-override: CreateShelfRequest
    bookstore.v1.CreateShelfResponse:
      description: The CreateShelfResponse message.
      properties:
        shelf:
          $ref: '#/components/schemas/bookstore.v1.Shelf'
      type: object
      x-speakeasy-name-override: CreateShelfResponse
    bookstore.v1.DeleteBookRequestInput:
      description: |2
         Request message for DeleteBook method.
      type: object
      x-speakeasy-name-override: DeleteBookRequest
    bookstore.v1.DeleteBookResponse:
      description: The DeleteBookResponse message.
      type: object
      x-speakeasy-name-override: DeleteBookResponse
    bookstore.v1.DeleteShelfRequestInput:
      description: |2
         Request message for DeleteShelf method.
      type: object
      x-speakeasy-name-override: DeleteShelfRequest
    bookstore.v1.DeleteShelfResponse:
      description: The DeleteShelfResponse message.
      type: object
      x-speakeasy-name-override: DeleteShelfResponse
    bookstore.v1.GetAuthorResponse:
      description: |
        The GetAuthorResponse message.

        This message contains a oneof named genre. Only a single field of the following list may be set at a time:
          - fiction
          - nonfiction
      properties:
        author:
          $ref: '#/components/schemas/bookstore.v1.Author'
        fiction:
          description: |-
            The fiction field.
            This field is part of the `genre` oneof.
            See the documentation for `bookstore.v1.GetAuthorResponse` for more details.
          nullable: true
          type: boolean
        nonfiction:
          description: |-
            The nonfiction field.
            This field is part of the `genre` oneof.
            See the documentation for `bookstore.v1.GetAuthorResponse` for more details.
          nullable: true
          type: boolean
      type: object
      x-speakeasy-name-override: GetAuthorResponse
    bookstore.v1.GetBookResponse:
      description: The GetBookResponse message.
      properties:
        book:
          $ref: '#/components/schemas/bookstore.v1.Book'
      type: object
      x-speakeasy-name-override: GetBookResponse
    bookstore.v1.ListShelvesResponse:
      description: |2
         Response to ListShelves call.
      properties:
        mask:
          nullable: true
          type: string
        shelves:
          description: |2
             Shelves in the bookstore.
          items:
            $ref: '#/components/schemas/bookstore.v1.Shelf'
          nullable: true
          type: array
      type: object
      x-speakeasy-name-override: ListShelvesResponse
    bookstore.v1.Shelf:
      description: |2
         A shelf resource.
      properties:
        id:
          description: |2
             A unique shelf id.
          format: int64
          type: string
        search%5Bencoded%5D:
          description: |2
             To test json name is percentage encoded
          type: string
        search[decoded]:
          description: |2
             To test json name is percentage decoded
          type: string
        theme:
          description: |2
             A theme of the shelf (fiction, poetry, etc).
          type: string
      type: object
      x-speakeasy-name-override: Shelf
    bookstore.v1.UpdateBookRequestInput:
      description: |2
         Request message for UpdateBook method
      properties:
        book:
          $ref: '#/components/schemas/bookstore.v1.Book'
      type: object
      x-speakeasy-name-override: UpdateBookRequest
    bookstore.v1.UpdateBookResponse:
      description: The UpdateBookResponse message.
      properties:
        book:
          $ref: '#/components/schemas/bookstore.v1.Book'
      type: object
      x-speakeasy-name-override: UpdateBookResponse
info:
  description: |
    This is an auto-generated API for bookstore.v1.BookstoreService.
  title: API For bookstore.v1.BookstoreService
  version: 0.0.1
openapi: 3.1.0
paths:
  /authors/{author}:
    get:
      description: |2
         Returns a specific author.
      operationId: bookstore.v1.BookstoreService.GetAuthor
      parameters:
        - in: path
          name: author
          required: true
          schema:
            description: |2
               The ID of the author resource to retrieve.
            format: int64
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.GetAuthorResponse'
          description: Successful response
      tags:
        - Bookstore
      x-speakeasy-group: Bookstore
      x-speakeasy-name-override: GetAuthor
  /shelf:
    post:
      description: |2
         Creates a new shelf in the bookstore.
      operationId: bookstore.v1.BookstoreService.CreateShelf
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bookstore.v1.CreateShelfRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.CreateShelfResponse'
          description: Successful response
      tags:
        - Bookstore
      x-speakeasy-group: Bookstore
      x-speakeasy-name-override: CreateShelf
  /shelves:
    get:
      description: |2
         Returns a list of all shelves in the bookstore.
      operationId: bookstore.v1.BookstoreService.ListShelves
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.ListShelvesResponse'
          description: |2
             Response to ListShelves call.
      tags:
        - Bookstore
      x-speakeasy-group: Bookstore
      x-speakeasy-name-override: ListShelves
  /shelves/{shelf}:
    delete:
      description: |2
         Deletes a shelf, including all books that are stored on the shelf.
      operationId: bookstore.v1.BookstoreService.DeleteShelf
      parameters:
        - in: path
          name: shelf
          required: true
          schema:
            description: |2
               The ID of the shelf to delete.
            format: int64
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bookstore.v1.DeleteShelfRequestInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.DeleteShelfResponse'
          description: Successful response
      tags:
        - Bookstore
      x-speakeasy-group: Bookstore
      x-speakeasy-name-override: DeleteShelf
  /shelves/{shelf}/books:
    post:
      description: |2
         Creates a new book.
      operationId: bookstore.v1.BookstoreService.CreateBook
      parameters:
        - in: path
          name: shelf
          required: true
          schema:
            description: |2
               The ID of the shelf on which to create a book.
            format: int64
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bookstore.v1.CreateBookRequestInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.CreateBookResponse'
          description: Successful response
      tags:
        - Bookstore
      x-speakeasy-entity-operation: Book#create
      x-speakeasy-group: Bookstore
      x-speakeasy-name-override: CreateBook
  /shelves/{shelf}/books/{book.id}:
    patch:
      description: Invokes the bookstore.v1.BookstoreService.UpdateBook method.
      operationId: bookstore.v1.BookstoreService.UpdateBook
      parameters:
        - in: path
          name: shelf
          required: true
          schema:
            description: |2
               The ID of the shelf from which to retrieve a book.
            format: int64
            type: string
        - in: path
          name: book.id
          required: true
          schema:
            description: |2
               A unique book id.
            format: int64
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bookstore.v1.UpdateBookRequestInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.UpdateBookResponse'
          description: Successful response
      tags:
        - Bookstore
      x-speakeasy-entity-operation: Book#update
      x-speakeasy-group: Bookstore
      x-speakeasy-name-override: UpdateBook
  /shelves/{shelf}/books/{book}:
    delete:
      description: |2
         Deletes a book from a shelf.
      operationId: bookstore.v1.BookstoreService.DeleteBook
      parameters:
        - in: path
          name: shelf
          required: true
          schema:
            description: |2
               The ID of the shelf from which to delete a book.
            format: int64
            type: string
        - in: path
          name: book
          required: true
          schema:
            description: |2
               The ID of the book to delete.
            format: int64
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bookstore.v1.DeleteBookRequestInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.DeleteBookResponse'
          description: Successful response
      tags:
        - Bookstore
      x-speakeasy-entity-operation: Book#delete
      x-speakeasy-group: Bookstore
      x-speakeasy-name-override: DeleteBook
    get:
      description: |2
         Returns a specific book.
      operationId: bookstore.v1.BookstoreService.GetBook
      parameters:
        - in: path
          name: shelf
          required: true
          schema:
            description: |2
               The ID of the shelf from which to retrieve a book.
            format: int64
            type: string
        - in: path
          name: book
          required: true
          schema:
            description: |2
               The ID of the book to retrieve.
            format: int64
            type: string
        - in: query
          name: author
          schema:
            description: The includeAuthor field.
            type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookstore.v1.GetBookResponse'
          description: Successful response
      tags:
        - Bookstore
      x-speakeasy-entity-operation: Book#read
      x-speakeasy-group: Bookstore
      x-speakeasy-name-override: GetBook
servers:
  - description: The server for bookstore.v1.BookstoreService.
    url: /
