// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: apigw/v1/apigw.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stability int32

const (
	Stability_STABILITY_UNSPECIFIED  Stability = 0
	Stability_STABILITY_STABLE       Stability = 1
	Stability_STABILITY_EXPERIMENTAL Stability = 2
	Stability_STABILITY_DEPRECATED   Stability = 3
)

// Enum value maps for Stability.
var (
	Stability_name = map[int32]string{
		0: "STABILITY_UNSPECIFIED",
		1: "STABILITY_STABLE",
		2: "STABILITY_EXPERIMENTAL",
		3: "STABILITY_DEPRECATED",
	}
	Stability_value = map[string]int32{
		"STABILITY_UNSPECIFIED":  0,
		"STABILITY_STABLE":       1,
		"STABILITY_EXPERIMENTAL": 2,
		"STABILITY_DEPRECATED":   3,
	}
)

func (x Stability) Enum() *Stability {
	p := new(Stability)
	*p = x
	return p
}

func (x Stability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stability) Descriptor() protoreflect.EnumDescriptor {
	return file_apigw_v1_apigw_proto_enumTypes[0].Descriptor()
}

func (Stability) Type() protoreflect.EnumType {
	return &file_apigw_v1_apigw_proto_enumTypes[0]
}

func (x Stability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stability.Descriptor instead.
func (Stability) EnumDescriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{0}
}

type MethodOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operations []*Operation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigw_v1_apigw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{0}
}

func (x *MethodOptions) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ServiceOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigw_v1_apigw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceOptions) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stability Stability `protobuf:"varint,1,opt,name=stability,proto3,enum=apigw.v1.Stability" json:"stability,omitempty"`
	DocsPath  string    `protobuf:"bytes,2,opt,name=docs_path,json=docsPath,proto3" json:"docs_path,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigw_v1_apigw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetStability() Stability {
	if x != nil {
		return x.Stability
	}
	return Stability_STABILITY_UNSPECIFIED
}

func (x *Service) GetDocsPath() string {
	if x != nil {
		return x.DocsPath
	}
	return ""
}

type Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method           string             `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Route            string             `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Stability        Stability          `protobuf:"varint,3,opt,name=stability,proto3,enum=apigw.v1.Stability" json:"stability,omitempty"`
	DocsPath         string             `protobuf:"bytes,4,opt,name=docs_path,json=docsPath,proto3" json:"docs_path,omitempty"`
	RequestExamples  []*RequestExample  `protobuf:"bytes,5,rep,name=request_examples,json=requestExamples,proto3" json:"request_examples,omitempty"`
	ResponseExamples []*ResponseExample `protobuf:"bytes,6,rep,name=response_examples,json=responseExamples,proto3" json:"response_examples,omitempty"`
}

func (x *Operation) Reset() {
	*x = Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigw_v1_apigw_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{3}
}

func (x *Operation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Operation) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Operation) GetStability() Stability {
	if x != nil {
		return x.Stability
	}
	return Stability_STABILITY_UNSPECIFIED
}

func (x *Operation) GetDocsPath() string {
	if x != nil {
		return x.DocsPath
	}
	return ""
}

func (x *Operation) GetRequestExamples() []*RequestExample {
	if x != nil {
		return x.RequestExamples
	}
	return nil
}

func (x *Operation) GetResponseExamples() []*ResponseExample {
	if x != nil {
		return x.ResponseExamples
	}
	return nil
}

type RequestExample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *RequestExample) Reset() {
	*x = RequestExample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigw_v1_apigw_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestExample) ProtoMessage() {}

func (x *RequestExample) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestExample.ProtoReflect.Descriptor instead.
func (*RequestExample) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{4}
}

func (x *RequestExample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestExample) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ResponseExample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ResponseExample) Reset() {
	*x = ResponseExample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigw_v1_apigw_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseExample) ProtoMessage() {}

func (x *ResponseExample) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseExample.ProtoReflect.Descriptor instead.
func (*ResponseExample) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseExample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseExample) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var file_apigw_v1_apigw_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         7650,
		Name:          "apigw.v1.service",
		Tag:           "bytes,7650,opt,name=service",
		Filename:      "apigw/v1/apigw.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         7651,
		Name:          "apigw.v1.method",
		Tag:           "bytes,7651,opt,name=method",
		Filename:      "apigw/v1/apigw.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional apigw.v1.ServiceOptions service = 7650;
	E_Service = &file_apigw_v1_apigw_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional apigw.v1.MethodOptions method = 7651;
	E_Method = &file_apigw_v1_apigw_proto_extTypes[1]
)

var File_apigw_v1_apigw_proto protoreflect.FileDescriptor

var file_apigw_v1_apigw_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x67, 0x77,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2e, 0x76, 0x31,
	0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x44, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x33, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3d, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70,
	0x69, 0x67, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x59, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x09, 0x73, 0x74, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x73, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x73, 0x50, 0x61,
	0x74, 0x68, 0x22, 0x96, 0x02, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x31,
	0x0a, 0x09, 0x73, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x09, 0x73, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x73, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x73, 0x50, 0x61, 0x74, 0x68, 0x12, 0x43,
	0x0a, 0x10, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x67, 0x77,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x52, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x11, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x10, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x39, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x2a, 0x72, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x19, 0x0a,
	0x15, 0x53, 0x54, 0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41, 0x42,
	0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x53, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x1a,
	0x0a, 0x16, 0x53, 0x54, 0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x45, 0x58, 0x50, 0x45,
	0x52, 0x49, 0x4d, 0x45, 0x4e, 0x54, 0x41, 0x4c, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x54,
	0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x44, 0x45, 0x50, 0x52, 0x45, 0x43, 0x41, 0x54,
	0x45, 0x44, 0x10, 0x03, 0x3a, 0x54, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xe2, 0x3b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3a, 0x50, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe3, 0x3b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70,
	0x69, 0x67, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x42, 0x89, 0x01, 0x0a,
	0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x41,
	0x70, 0x69, 0x67, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x6e, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x67, 0x77,
	0x2f, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa,
	0x02, 0x08, 0x41, 0x70, 0x69, 0x67, 0x77, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x08, 0x41, 0x70, 0x69,
	0x67, 0x77, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x41, 0x70, 0x69, 0x67, 0x77, 0x5c, 0x56, 0x31,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x41,
	0x70, 0x69, 0x67, 0x77, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apigw_v1_apigw_proto_rawDescOnce sync.Once
	file_apigw_v1_apigw_proto_rawDescData = file_apigw_v1_apigw_proto_rawDesc
)

func file_apigw_v1_apigw_proto_rawDescGZIP() []byte {
	file_apigw_v1_apigw_proto_rawDescOnce.Do(func() {
		file_apigw_v1_apigw_proto_rawDescData = protoimpl.X.CompressGZIP(file_apigw_v1_apigw_proto_rawDescData)
	})
	return file_apigw_v1_apigw_proto_rawDescData
}

var file_apigw_v1_apigw_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apigw_v1_apigw_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apigw_v1_apigw_proto_goTypes = []interface{}{
	(Stability)(0),                      // 0: apigw.v1.Stability
	(*MethodOptions)(nil),               // 1: apigw.v1.MethodOptions
	(*ServiceOptions)(nil),              // 2: apigw.v1.ServiceOptions
	(*Service)(nil),                     // 3: apigw.v1.Service
	(*Operation)(nil),                   // 4: apigw.v1.Operation
	(*RequestExample)(nil),              // 5: apigw.v1.RequestExample
	(*ResponseExample)(nil),             // 6: apigw.v1.ResponseExample
	(*descriptorpb.ServiceOptions)(nil), // 7: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 8: google.protobuf.MethodOptions
}
var file_apigw_v1_apigw_proto_depIdxs = []int32{
	4,  // 0: apigw.v1.MethodOptions.operations:type_name -> apigw.v1.Operation
	3,  // 1: apigw.v1.ServiceOptions.service:type_name -> apigw.v1.Service
	0,  // 2: apigw.v1.Service.stability:type_name -> apigw.v1.Stability
	0,  // 3: apigw.v1.Operation.stability:type_name -> apigw.v1.Stability
	5,  // 4: apigw.v1.Operation.request_examples:type_name -> apigw.v1.RequestExample
	6,  // 5: apigw.v1.Operation.response_examples:type_name -> apigw.v1.ResponseExample
	7,  // 6: apigw.v1.service:extendee -> google.protobuf.ServiceOptions
	8,  // 7: apigw.v1.method:extendee -> google.protobuf.MethodOptions
	2,  // 8: apigw.v1.service:type_name -> apigw.v1.ServiceOptions
	1,  // 9: apigw.v1.method:type_name -> apigw.v1.MethodOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	8,  // [8:10] is the sub-list for extension type_name
	6,  // [6:8] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_apigw_v1_apigw_proto_init() }
func file_apigw_v1_apigw_proto_init() {
	if File_apigw_v1_apigw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apigw_v1_apigw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apigw_v1_apigw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apigw_v1_apigw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apigw_v1_apigw_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apigw_v1_apigw_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestExample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apigw_v1_apigw_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseExample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apigw_v1_apigw_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_apigw_v1_apigw_proto_goTypes,
		DependencyIndexes: file_apigw_v1_apigw_proto_depIdxs,
		EnumInfos:         file_apigw_v1_apigw_proto_enumTypes,
		MessageInfos:      file_apigw_v1_apigw_proto_msgTypes,
		ExtensionInfos:    file_apigw_v1_apigw_proto_extTypes,
	}.Build()
	File_apigw_v1_apigw_proto = out.File
	file_apigw_v1_apigw_proto_rawDesc = nil
	file_apigw_v1_apigw_proto_goTypes = nil
	file_apigw_v1_apigw_proto_depIdxs = nil
}
