// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: apigw/v1/apigw.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stability int32

const (
	Stability_STABILITY_UNSPECIFIED  Stability = 0
	Stability_STABILITY_STABLE       Stability = 1
	Stability_STABILITY_EXPERIMENTAL Stability = 2
	Stability_STABILITY_DEPRECATED   Stability = 3
)

// Enum value maps for Stability.
var (
	Stability_name = map[int32]string{
		0: "STABILITY_UNSPECIFIED",
		1: "STABILITY_STABLE",
		2: "STABILITY_EXPERIMENTAL",
		3: "STABILITY_DEPRECATED",
	}
	Stability_value = map[string]int32{
		"STABILITY_UNSPECIFIED":  0,
		"STABILITY_STABLE":       1,
		"STABILITY_EXPERIMENTAL": 2,
		"STABILITY_DEPRECATED":   3,
	}
)

func (x Stability) Enum() *Stability {
	p := new(Stability)
	*p = x
	return p
}

func (x Stability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stability) Descriptor() protoreflect.EnumDescriptor {
	return file_apigw_v1_apigw_proto_enumTypes[0].Descriptor()
}

func (Stability) Type() protoreflect.EnumType {
	return &file_apigw_v1_apigw_proto_enumTypes[0]
}

func (x Stability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stability.Descriptor instead.
func (Stability) EnumDescriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{0}
}

type TerraformEntity_TerraformEntityMethodType int32

const (
	TerraformEntity_TERRAFORM_ENTITY_METHOD_TYPE_UNSPECIFIED TerraformEntity_TerraformEntityMethodType = 0
	TerraformEntity_TERRAFORM_ENTITY_METHOD_TYPE_CREATE      TerraformEntity_TerraformEntityMethodType = 1
	TerraformEntity_TERRAFORM_ENTITY_METHOD_TYPE_READ        TerraformEntity_TerraformEntityMethodType = 2
	TerraformEntity_TERRAFORM_ENTITY_METHOD_TYPE_UPDATE      TerraformEntity_TerraformEntityMethodType = 3
	TerraformEntity_TERRAFORM_ENTITY_METHOD_TYPE_DELETE      TerraformEntity_TerraformEntityMethodType = 4
)

// Enum value maps for TerraformEntity_TerraformEntityMethodType.
var (
	TerraformEntity_TerraformEntityMethodType_name = map[int32]string{
		0: "TERRAFORM_ENTITY_METHOD_TYPE_UNSPECIFIED",
		1: "TERRAFORM_ENTITY_METHOD_TYPE_CREATE",
		2: "TERRAFORM_ENTITY_METHOD_TYPE_READ",
		3: "TERRAFORM_ENTITY_METHOD_TYPE_UPDATE",
		4: "TERRAFORM_ENTITY_METHOD_TYPE_DELETE",
	}
	TerraformEntity_TerraformEntityMethodType_value = map[string]int32{
		"TERRAFORM_ENTITY_METHOD_TYPE_UNSPECIFIED": 0,
		"TERRAFORM_ENTITY_METHOD_TYPE_CREATE":      1,
		"TERRAFORM_ENTITY_METHOD_TYPE_READ":        2,
		"TERRAFORM_ENTITY_METHOD_TYPE_UPDATE":      3,
		"TERRAFORM_ENTITY_METHOD_TYPE_DELETE":      4,
	}
)

func (x TerraformEntity_TerraformEntityMethodType) Enum() *TerraformEntity_TerraformEntityMethodType {
	p := new(TerraformEntity_TerraformEntityMethodType)
	*p = x
	return p
}

func (x TerraformEntity_TerraformEntityMethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerraformEntity_TerraformEntityMethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_apigw_v1_apigw_proto_enumTypes[1].Descriptor()
}

func (TerraformEntity_TerraformEntityMethodType) Type() protoreflect.EnumType {
	return &file_apigw_v1_apigw_proto_enumTypes[1]
}

func (x TerraformEntity_TerraformEntityMethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerraformEntity_TerraformEntityMethodType.Descriptor instead.
func (TerraformEntity_TerraformEntityMethodType) EnumDescriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{7, 0}
}

type TerraformEntity_OptionalExclusion int32

const (
	TerraformEntity_OPTIONAL_EXCLUSION_UNSPECIFIED TerraformEntity_OptionalExclusion = 0
	// Exclude the field from the terraform resource
	TerraformEntity_OPTIONAL_EXCLUSION_RESOURCE_ONLY TerraformEntity_OptionalExclusion = 1
	// Exclude the field from the terraform data source
	TerraformEntity_OPTIONAL_EXCLUSION_DATA_SOURCE_ONLY TerraformEntity_OptionalExclusion = 2
)

// Enum value maps for TerraformEntity_OptionalExclusion.
var (
	TerraformEntity_OptionalExclusion_name = map[int32]string{
		0: "OPTIONAL_EXCLUSION_UNSPECIFIED",
		1: "OPTIONAL_EXCLUSION_RESOURCE_ONLY",
		2: "OPTIONAL_EXCLUSION_DATA_SOURCE_ONLY",
	}
	TerraformEntity_OptionalExclusion_value = map[string]int32{
		"OPTIONAL_EXCLUSION_UNSPECIFIED":      0,
		"OPTIONAL_EXCLUSION_RESOURCE_ONLY":    1,
		"OPTIONAL_EXCLUSION_DATA_SOURCE_ONLY": 2,
	}
)

func (x TerraformEntity_OptionalExclusion) Enum() *TerraformEntity_OptionalExclusion {
	p := new(TerraformEntity_OptionalExclusion)
	*p = x
	return p
}

func (x TerraformEntity_OptionalExclusion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerraformEntity_OptionalExclusion) Descriptor() protoreflect.EnumDescriptor {
	return file_apigw_v1_apigw_proto_enumTypes[2].Descriptor()
}

func (TerraformEntity_OptionalExclusion) Type() protoreflect.EnumType {
	return &file_apigw_v1_apigw_proto_enumTypes[2]
}

func (x TerraformEntity_OptionalExclusion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerraformEntity_OptionalExclusion.Descriptor instead.
func (TerraformEntity_OptionalExclusion) EnumDescriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{7, 1}
}

type MessageOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageOptions []*MessageOption       `protobuf:"bytes,1,rep,name=message_options,json=messageOptions,proto3" json:"message_options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_apigw_v1_apigw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{0}
}

func (x *MessageOptions) GetMessageOptions() []*MessageOption {
	if x != nil {
		return x.MessageOptions
	}
	return nil
}

type MessageOption struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TerraformEntity *TerraformEntity       `protobuf:"bytes,1,opt,name=terraform_entity,json=terraformEntity,proto3" json:"terraform_entity,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Messages are only exposed if they are in (or descend from) an RPC service.
	// This option overrides that by forcing generation of this (and referenced) message.
	ForceExpose bool `protobuf:"varint,3,opt,name=force_expose,json=forceExpose,proto3" json:"force_expose,omitempty"`
	// Set this to process this message as the body of a webhook
	WebhookRequestName string `protobuf:"bytes,4,opt,name=webhook_request_name,json=webhookRequestName,proto3" json:"webhook_request_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MessageOption) Reset() {
	*x = MessageOption{}
	mi := &file_apigw_v1_apigw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOption) ProtoMessage() {}

func (x *MessageOption) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOption.ProtoReflect.Descriptor instead.
func (*MessageOption) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{1}
}

func (x *MessageOption) GetTerraformEntity() *TerraformEntity {
	if x != nil {
		return x.TerraformEntity
	}
	return nil
}

func (x *MessageOption) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MessageOption) GetForceExpose() bool {
	if x != nil {
		return x.ForceExpose
	}
	return false
}

func (x *MessageOption) GetWebhookRequestName() string {
	if x != nil {
		return x.WebhookRequestName
	}
	return ""
}

type FieldOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sets the field as required in the generated openAPI spec.
	RequiredSpec bool `protobuf:"varint,1,opt,name=required_spec,json=requiredSpec,proto3" json:"required_spec,omitempty"`
	// Sets the field as read only in the generated openAPI spec.
	ReadOnlySpec  bool `protobuf:"varint,2,opt,name=read_only_spec,json=readOnlySpec,proto3" json:"read_only_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOption) Reset() {
	*x = FieldOption{}
	mi := &file_apigw_v1_apigw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption) ProtoMessage() {}

func (x *FieldOption) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption.ProtoReflect.Descriptor instead.
func (*FieldOption) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOption) GetRequiredSpec() bool {
	if x != nil {
		return x.RequiredSpec
	}
	return false
}

func (x *FieldOption) GetReadOnlySpec() bool {
	if x != nil {
		return x.ReadOnlySpec
	}
	return false
}

type FieldOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldOptions  []*FieldOption         `protobuf:"bytes,1,rep,name=field_options,json=fieldOptions,proto3" json:"field_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_apigw_v1_apigw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{3}
}

func (x *FieldOptions) GetFieldOptions() []*FieldOption {
	if x != nil {
		return x.FieldOptions
	}
	return nil
}

type MethodOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*Operation           `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_apigw_v1_apigw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{4}
}

func (x *MethodOptions) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ServiceOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_apigw_v1_apigw_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceOptions) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stability     Stability              `protobuf:"varint,1,opt,name=stability,proto3,enum=apigw.v1.Stability" json:"stability,omitempty"`
	DocsPath      string                 `protobuf:"bytes,2,opt,name=docs_path,json=docsPath,proto3" json:"docs_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_apigw_v1_apigw_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{6}
}

func (x *Service) GetStability() Stability {
	if x != nil {
		return x.Stability
	}
	return Stability_STABILITY_UNSPECIFIED
}

func (x *Service) GetDocsPath() string {
	if x != nil {
		return x.DocsPath
	}
	return ""
}

type TerraformEntity struct {
	state             protoimpl.MessageState                    `protogen:"open.v1"`
	Type              TerraformEntity_TerraformEntityMethodType `protobuf:"varint,1,opt,name=type,proto3,enum=apigw.v1.TerraformEntity_TerraformEntityMethodType" json:"type,omitempty"`
	Name              string                                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Json              bool                                      `protobuf:"varint,3,opt,name=json,proto3" json:"json,omitempty"`
	OperationNumber   int32                                     `protobuf:"varint,4,opt,name=operation_number,json=operationNumber,proto3" json:"operation_number,omitempty"`
	OptionalExclusion TerraformEntity_OptionalExclusion         `protobuf:"varint,5,opt,name=optional_exclusion,json=optionalExclusion,proto3,enum=apigw.v1.TerraformEntity_OptionalExclusion" json:"optional_exclusion,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TerraformEntity) Reset() {
	*x = TerraformEntity{}
	mi := &file_apigw_v1_apigw_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerraformEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerraformEntity) ProtoMessage() {}

func (x *TerraformEntity) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerraformEntity.ProtoReflect.Descriptor instead.
func (*TerraformEntity) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{7}
}

func (x *TerraformEntity) GetType() TerraformEntity_TerraformEntityMethodType {
	if x != nil {
		return x.Type
	}
	return TerraformEntity_TERRAFORM_ENTITY_METHOD_TYPE_UNSPECIFIED
}

func (x *TerraformEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TerraformEntity) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *TerraformEntity) GetOperationNumber() int32 {
	if x != nil {
		return x.OperationNumber
	}
	return 0
}

func (x *TerraformEntity) GetOptionalExclusion() TerraformEntity_OptionalExclusion {
	if x != nil {
		return x.OptionalExclusion
	}
	return TerraformEntity_OPTIONAL_EXCLUSION_UNSPECIFIED
}

type Operation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Method           string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Route            string                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Query            map[string]string      `protobuf:"bytes,3,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Stability        Stability              `protobuf:"varint,4,opt,name=stability,proto3,enum=apigw.v1.Stability" json:"stability,omitempty"`
	DocsPath         string                 `protobuf:"bytes,5,opt,name=docs_path,json=docsPath,proto3" json:"docs_path,omitempty"`
	RequestExamples  []*RequestExample      `protobuf:"bytes,6,rep,name=request_examples,json=requestExamples,proto3" json:"request_examples,omitempty"`
	ResponseExamples []*ResponseExample     `protobuf:"bytes,7,rep,name=response_examples,json=responseExamples,proto3" json:"response_examples,omitempty"`
	TerraformEntity  []*TerraformEntity     `protobuf:"bytes,8,rep,name=terraform_entity,json=terraformEntity,proto3" json:"terraform_entity,omitempty"`
	Summary          string                 `protobuf:"bytes,9,opt,name=summary,proto3" json:"summary,omitempty"`
	Group            string                 `protobuf:"bytes,10,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_apigw_v1_apigw_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{8}
}

func (x *Operation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Operation) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Operation) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *Operation) GetStability() Stability {
	if x != nil {
		return x.Stability
	}
	return Stability_STABILITY_UNSPECIFIED
}

func (x *Operation) GetDocsPath() string {
	if x != nil {
		return x.DocsPath
	}
	return ""
}

func (x *Operation) GetRequestExamples() []*RequestExample {
	if x != nil {
		return x.RequestExamples
	}
	return nil
}

func (x *Operation) GetResponseExamples() []*ResponseExample {
	if x != nil {
		return x.ResponseExamples
	}
	return nil
}

func (x *Operation) GetTerraformEntity() []*TerraformEntity {
	if x != nil {
		return x.TerraformEntity
	}
	return nil
}

func (x *Operation) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Operation) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type RequestExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestExample) Reset() {
	*x = RequestExample{}
	mi := &file_apigw_v1_apigw_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestExample) ProtoMessage() {}

func (x *RequestExample) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestExample.ProtoReflect.Descriptor instead.
func (*RequestExample) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{9}
}

func (x *RequestExample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestExample) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ResponseExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseExample) Reset() {
	*x = ResponseExample{}
	mi := &file_apigw_v1_apigw_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseExample) ProtoMessage() {}

func (x *ResponseExample) ProtoReflect() protoreflect.Message {
	mi := &file_apigw_v1_apigw_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseExample.ProtoReflect.Descriptor instead.
func (*ResponseExample) Descriptor() ([]byte, []int) {
	return file_apigw_v1_apigw_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseExample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseExample) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var file_apigw_v1_apigw_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         7650,
		Name:          "apigw.v1.service",
		Tag:           "bytes,7650,opt,name=service",
		Filename:      "apigw/v1/apigw.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         7651,
		Name:          "apigw.v1.method",
		Tag:           "bytes,7651,opt,name=method",
		Filename:      "apigw/v1/apigw.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         7652,
		Name:          "apigw.v1.field",
		Tag:           "bytes,7652,opt,name=field",
		Filename:      "apigw/v1/apigw.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         7653,
		Name:          "apigw.v1.message",
		Tag:           "bytes,7653,opt,name=message",
		Filename:      "apigw/v1/apigw.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional apigw.v1.ServiceOptions service = 7650;
	E_Service = &file_apigw_v1_apigw_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional apigw.v1.MethodOptions method = 7651;
	E_Method = &file_apigw_v1_apigw_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional apigw.v1.FieldOptions field = 7652;
	E_Field = &file_apigw_v1_apigw_proto_extTypes[2]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional apigw.v1.MessageOptions message = 7653;
	E_Message = &file_apigw_v1_apigw_proto_extTypes[3]
)

var File_apigw_v1_apigw_proto protoreflect.FileDescriptor

const file_apigw_v1_apigw_proto_rawDesc = "" +
	"\n" +
	"\x14apigw/v1/apigw.proto\x12\bapigw.v1\x1a google/protobuf/descriptor.proto\"R\n" +
	"\x0eMessageOptions\x12@\n" +
	"\x0fmessage_options\x18\x01 \x03(\v2\x17.apigw.v1.MessageOptionR\x0emessageOptions\"\xc0\x01\n" +
	"\rMessageOption\x12D\n" +
	"\x10terraform_entity\x18\x01 \x01(\v2\x19.apigw.v1.TerraformEntityR\x0fterraformEntity\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fforce_expose\x18\x03 \x01(\bR\vforceExpose\x120\n" +
	"\x14webhook_request_name\x18\x04 \x01(\tR\x12webhookRequestName\"X\n" +
	"\vFieldOption\x12#\n" +
	"\rrequired_spec\x18\x01 \x01(\bR\frequiredSpec\x12$\n" +
	"\x0eread_only_spec\x18\x02 \x01(\bR\freadOnlySpec\"J\n" +
	"\fFieldOptions\x12:\n" +
	"\rfield_options\x18\x01 \x03(\v2\x15.apigw.v1.FieldOptionR\ffieldOptions\"D\n" +
	"\rMethodOptions\x123\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x13.apigw.v1.OperationR\n" +
	"operations\"=\n" +
	"\x0eServiceOptions\x12+\n" +
	"\aservice\x18\x01 \x01(\v2\x11.apigw.v1.ServiceR\aservice\"Y\n" +
	"\aService\x121\n" +
	"\tstability\x18\x01 \x01(\x0e2\x13.apigw.v1.StabilityR\tstability\x12\x1b\n" +
	"\tdocs_path\x18\x02 \x01(\tR\bdocsPath\"\x80\x05\n" +
	"\x0fTerraformEntity\x12G\n" +
	"\x04type\x18\x01 \x01(\x0e23.apigw.v1.TerraformEntity.TerraformEntityMethodTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04json\x18\x03 \x01(\bR\x04json\x12)\n" +
	"\x10operation_number\x18\x04 \x01(\x05R\x0foperationNumber\x12Z\n" +
	"\x12optional_exclusion\x18\x05 \x01(\x0e2+.apigw.v1.TerraformEntity.OptionalExclusionR\x11optionalExclusion\"\xeb\x01\n" +
	"\x19TerraformEntityMethodType\x12,\n" +
	"(TERRAFORM_ENTITY_METHOD_TYPE_UNSPECIFIED\x10\x00\x12'\n" +
	"#TERRAFORM_ENTITY_METHOD_TYPE_CREATE\x10\x01\x12%\n" +
	"!TERRAFORM_ENTITY_METHOD_TYPE_READ\x10\x02\x12'\n" +
	"#TERRAFORM_ENTITY_METHOD_TYPE_UPDATE\x10\x03\x12'\n" +
	"#TERRAFORM_ENTITY_METHOD_TYPE_DELETE\x10\x04\"\x86\x01\n" +
	"\x11OptionalExclusion\x12\"\n" +
	"\x1eOPTIONAL_EXCLUSION_UNSPECIFIED\x10\x00\x12$\n" +
	" OPTIONAL_EXCLUSION_RESOURCE_ONLY\x10\x01\x12'\n" +
	"#OPTIONAL_EXCLUSION_DATA_SOURCE_ONLY\x10\x02\"\xfc\x03\n" +
	"\tOperation\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x14\n" +
	"\x05route\x18\x02 \x01(\tR\x05route\x124\n" +
	"\x05query\x18\x03 \x03(\v2\x1e.apigw.v1.Operation.QueryEntryR\x05query\x121\n" +
	"\tstability\x18\x04 \x01(\x0e2\x13.apigw.v1.StabilityR\tstability\x12\x1b\n" +
	"\tdocs_path\x18\x05 \x01(\tR\bdocsPath\x12C\n" +
	"\x10request_examples\x18\x06 \x03(\v2\x18.apigw.v1.RequestExampleR\x0frequestExamples\x12F\n" +
	"\x11response_examples\x18\a \x03(\v2\x19.apigw.v1.ResponseExampleR\x10responseExamples\x12D\n" +
	"\x10terraform_entity\x18\b \x03(\v2\x19.apigw.v1.TerraformEntityR\x0fterraformEntity\x12\x18\n" +
	"\asummary\x18\t \x01(\tR\asummary\x12\x14\n" +
	"\x05group\x18\n" +
	" \x01(\tR\x05group\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x0eRequestExample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"9\n" +
	"\x0fResponseExample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path*r\n" +
	"\tStability\x12\x19\n" +
	"\x15STABILITY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STABILITY_STABLE\x10\x01\x12\x1a\n" +
	"\x16STABILITY_EXPERIMENTAL\x10\x02\x12\x18\n" +
	"\x14STABILITY_DEPRECATED\x10\x03:T\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xe2; \x01(\v2\x18.apigw.v1.ServiceOptionsR\aservice:P\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18\xe3; \x01(\v2\x17.apigw.v1.MethodOptionsR\x06method:L\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xe4; \x01(\v2\x16.apigw.v1.FieldOptionsR\x05field:T\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xe5; \x01(\v2\x18.apigw.v1.MessageOptionsR\amessageB\x89\x01\n" +
	"\fcom.apigw.v1B\n" +
	"ApigwProtoP\x01Z,github.com/ductone/protoc-gen-apigw/apigw/v1\xa2\x02\x03AXX\xaa\x02\bApigw.V1\xca\x02\bApigw\\V1\xe2\x02\x14Apigw\\V1\\GPBMetadata\xea\x02\tApigw::V1b\x06proto3"

var (
	file_apigw_v1_apigw_proto_rawDescOnce sync.Once
	file_apigw_v1_apigw_proto_rawDescData []byte
)

func file_apigw_v1_apigw_proto_rawDescGZIP() []byte {
	file_apigw_v1_apigw_proto_rawDescOnce.Do(func() {
		file_apigw_v1_apigw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apigw_v1_apigw_proto_rawDesc), len(file_apigw_v1_apigw_proto_rawDesc)))
	})
	return file_apigw_v1_apigw_proto_rawDescData
}

var file_apigw_v1_apigw_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_apigw_v1_apigw_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_apigw_v1_apigw_proto_goTypes = []any{
	(Stability)(0), // 0: apigw.v1.Stability
	(TerraformEntity_TerraformEntityMethodType)(0), // 1: apigw.v1.TerraformEntity.TerraformEntityMethodType
	(TerraformEntity_OptionalExclusion)(0),         // 2: apigw.v1.TerraformEntity.OptionalExclusion
	(*MessageOptions)(nil),                         // 3: apigw.v1.MessageOptions
	(*MessageOption)(nil),                          // 4: apigw.v1.MessageOption
	(*FieldOption)(nil),                            // 5: apigw.v1.FieldOption
	(*FieldOptions)(nil),                           // 6: apigw.v1.FieldOptions
	(*MethodOptions)(nil),                          // 7: apigw.v1.MethodOptions
	(*ServiceOptions)(nil),                         // 8: apigw.v1.ServiceOptions
	(*Service)(nil),                                // 9: apigw.v1.Service
	(*TerraformEntity)(nil),                        // 10: apigw.v1.TerraformEntity
	(*Operation)(nil),                              // 11: apigw.v1.Operation
	(*RequestExample)(nil),                         // 12: apigw.v1.RequestExample
	(*ResponseExample)(nil),                        // 13: apigw.v1.ResponseExample
	nil,                                            // 14: apigw.v1.Operation.QueryEntry
	(*descriptorpb.ServiceOptions)(nil),            // 15: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),             // 16: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),              // 17: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil),            // 18: google.protobuf.MessageOptions
}
var file_apigw_v1_apigw_proto_depIdxs = []int32{
	4,  // 0: apigw.v1.MessageOptions.message_options:type_name -> apigw.v1.MessageOption
	10, // 1: apigw.v1.MessageOption.terraform_entity:type_name -> apigw.v1.TerraformEntity
	5,  // 2: apigw.v1.FieldOptions.field_options:type_name -> apigw.v1.FieldOption
	11, // 3: apigw.v1.MethodOptions.operations:type_name -> apigw.v1.Operation
	9,  // 4: apigw.v1.ServiceOptions.service:type_name -> apigw.v1.Service
	0,  // 5: apigw.v1.Service.stability:type_name -> apigw.v1.Stability
	1,  // 6: apigw.v1.TerraformEntity.type:type_name -> apigw.v1.TerraformEntity.TerraformEntityMethodType
	2,  // 7: apigw.v1.TerraformEntity.optional_exclusion:type_name -> apigw.v1.TerraformEntity.OptionalExclusion
	14, // 8: apigw.v1.Operation.query:type_name -> apigw.v1.Operation.QueryEntry
	0,  // 9: apigw.v1.Operation.stability:type_name -> apigw.v1.Stability
	12, // 10: apigw.v1.Operation.request_examples:type_name -> apigw.v1.RequestExample
	13, // 11: apigw.v1.Operation.response_examples:type_name -> apigw.v1.ResponseExample
	10, // 12: apigw.v1.Operation.terraform_entity:type_name -> apigw.v1.TerraformEntity
	15, // 13: apigw.v1.service:extendee -> google.protobuf.ServiceOptions
	16, // 14: apigw.v1.method:extendee -> google.protobuf.MethodOptions
	17, // 15: apigw.v1.field:extendee -> google.protobuf.FieldOptions
	18, // 16: apigw.v1.message:extendee -> google.protobuf.MessageOptions
	8,  // 17: apigw.v1.service:type_name -> apigw.v1.ServiceOptions
	7,  // 18: apigw.v1.method:type_name -> apigw.v1.MethodOptions
	6,  // 19: apigw.v1.field:type_name -> apigw.v1.FieldOptions
	3,  // 20: apigw.v1.message:type_name -> apigw.v1.MessageOptions
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	17, // [17:21] is the sub-list for extension type_name
	13, // [13:17] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_apigw_v1_apigw_proto_init() }
func file_apigw_v1_apigw_proto_init() {
	if File_apigw_v1_apigw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apigw_v1_apigw_proto_rawDesc), len(file_apigw_v1_apigw_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_apigw_v1_apigw_proto_goTypes,
		DependencyIndexes: file_apigw_v1_apigw_proto_depIdxs,
		EnumInfos:         file_apigw_v1_apigw_proto_enumTypes,
		MessageInfos:      file_apigw_v1_apigw_proto_msgTypes,
		ExtensionInfos:    file_apigw_v1_apigw_proto_extTypes,
	}.Build()
	File_apigw_v1_apigw_proto = out.File
	file_apigw_v1_apigw_proto_goTypes = nil
	file_apigw_v1_apigw_proto_depIdxs = nil
}
