// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bookstore/v2/bookstore.proto

package v2

import (
	_ "github.com/ductone/protoc-gen-apigw/apigw/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for v2 ListShelves.
type ListShelvesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShelvesRequest) Reset() {
	*x = ListShelvesRequest{}
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShelvesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShelvesRequest) ProtoMessage() {}

func (x *ListShelvesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShelvesRequest.ProtoReflect.Descriptor instead.
func (*ListShelvesRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_v2_bookstore_proto_rawDescGZIP(), []int{0}
}

// Response message for v2 ListShelves.
type ListShelvesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShelfIds      []string               `protobuf:"bytes,1,rep,name=shelf_ids,json=shelfIds,proto3" json:"shelf_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShelvesResponse) Reset() {
	*x = ListShelvesResponse{}
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShelvesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShelvesResponse) ProtoMessage() {}

func (x *ListShelvesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShelvesResponse.ProtoReflect.Descriptor instead.
func (*ListShelvesResponse) Descriptor() ([]byte, []int) {
	return file_bookstore_v2_bookstore_proto_rawDescGZIP(), []int{1}
}

func (x *ListShelvesResponse) GetShelfIds() []string {
	if x != nil {
		return x.ShelfIds
	}
	return nil
}

// Request message for v2 CreateShelf.
type CreateShelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShelfRequest) Reset() {
	*x = CreateShelfRequest{}
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfRequest) ProtoMessage() {}

func (x *CreateShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfRequest.ProtoReflect.Descriptor instead.
func (*CreateShelfRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_v2_bookstore_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShelfRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

// Response message for v2 CreateShelf.
type CreateShelfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShelfId       string                 `protobuf:"bytes,1,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShelfResponse) Reset() {
	*x = CreateShelfResponse{}
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfResponse) ProtoMessage() {}

func (x *CreateShelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfResponse.ProtoReflect.Descriptor instead.
func (*CreateShelfResponse) Descriptor() ([]byte, []int) {
	return file_bookstore_v2_bookstore_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShelfResponse) GetShelfId() string {
	if x != nil {
		return x.ShelfId
	}
	return ""
}

// Request message for v2 GetShelf.
type GetShelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         string                 `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfRequest) Reset() {
	*x = GetShelfRequest{}
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfRequest) ProtoMessage() {}

func (x *GetShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfRequest.ProtoReflect.Descriptor instead.
func (*GetShelfRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_v2_bookstore_proto_rawDescGZIP(), []int{4}
}

func (x *GetShelfRequest) GetShelf() string {
	if x != nil {
		return x.Shelf
	}
	return ""
}

// Response message for v2 GetShelf.
type GetShelfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShelfId       string                 `protobuf:"bytes,1,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	Theme         string                 `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfResponse) Reset() {
	*x = GetShelfResponse{}
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfResponse) ProtoMessage() {}

func (x *GetShelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v2_bookstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfResponse.ProtoReflect.Descriptor instead.
func (*GetShelfResponse) Descriptor() ([]byte, []int) {
	return file_bookstore_v2_bookstore_proto_rawDescGZIP(), []int{5}
}

func (x *GetShelfResponse) GetShelfId() string {
	if x != nil {
		return x.ShelfId
	}
	return ""
}

func (x *GetShelfResponse) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

var File_bookstore_v2_bookstore_proto protoreflect.FileDescriptor

const file_bookstore_v2_bookstore_proto_rawDesc = "" +
	"\n" +
	"\x1cbookstore/v2/bookstore.proto\x12\fbookstore.v2\x1a\x14apigw/v1/apigw.proto\"2\n" +
	"\x12ListShelvesRequest:\x1c\xaa\xde\x03\x18\n" +
	"\x16*\x14ListShelvesRequestV2\"Q\n" +
	"\x13ListShelvesResponse\x12\x1b\n" +
	"\tshelf_ids\x18\x01 \x03(\tR\bshelfIds:\x1d\xaa\xde\x03\x19\n" +
	"\x17*\x15ListShelvesResponseV2\"H\n" +
	"\x12CreateShelfRequest\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme:\x1c\xaa\xde\x03\x18\n" +
	"\x16*\x14CreateShelfRequestV2\"O\n" +
	"\x13CreateShelfResponse\x12\x19\n" +
	"\bshelf_id\x18\x01 \x01(\tR\ashelfId:\x1d\xaa\xde\x03\x19\n" +
	"\x17*\x15CreateShelfResponseV2\"B\n" +
	"\x0fGetShelfRequest\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\tR\x05shelf:\x19\xaa\xde\x03\x15\n" +
	"\x13*\x11GetShelfRequestV2\"_\n" +
	"\x10GetShelfResponse\x12\x19\n" +
	"\bshelf_id\x18\x01 \x01(\tR\ashelfId\x12\x14\n" +
	"\x05theme\x18\x02 \x01(\tR\x05theme:\x1a\xaa\xde\x03\x16\n" +
	"\x14*\x12GetShelfResponseV22\xc4\x03\n" +
	"\x10BookstoreService\x12z\n" +
	"\vListShelves\x12 .bookstore.v2.ListShelvesRequest\x1a!.bookstore.v2.ListShelvesResponse\"&\x9a\xde\x03\"\n" +
	" \n" +
	"\x03GET\x12\v/v2/shelves \x01R\n" +
	"Shelves V2\x12\x8d\x01\n" +
	"\vCreateShelf\x12 .bookstore.v2.CreateShelfRequest\x1a!.bookstore.v2.CreateShelfResponse\"9\x9a\xde\x035\n" +
	"3\n" +
	"\x04POST\x12\v/v2/shelves \x01R\n" +
	"Shelves V2r\x10CreateShelfDraft\x12\x8c\x01\n" +
	"\bGetShelf\x12\x1d.bookstore.v2.GetShelfRequest\x1a\x1e.bookstore.v2.GetShelfResponse\"A\x9a\xde\x03=\n" +
	";\n" +
	"\x03GET\x12\x13/v2/shelves/{shelf} \x01R\n" +
	"Shelves V2j\x11BookstoreV2Lookup\x1a\x15\x92\xde\x03\x11\n" +
	"\x0f\b\x01\"\vBookstoreV2B:Z8github.com/ductone/protoc-gen-apigw/example/bookstore/v2b\x06proto3"

var (
	file_bookstore_v2_bookstore_proto_rawDescOnce sync.Once
	file_bookstore_v2_bookstore_proto_rawDescData []byte
)

func file_bookstore_v2_bookstore_proto_rawDescGZIP() []byte {
	file_bookstore_v2_bookstore_proto_rawDescOnce.Do(func() {
		file_bookstore_v2_bookstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bookstore_v2_bookstore_proto_rawDesc), len(file_bookstore_v2_bookstore_proto_rawDesc)))
	})
	return file_bookstore_v2_bookstore_proto_rawDescData
}

var file_bookstore_v2_bookstore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bookstore_v2_bookstore_proto_goTypes = []any{
	(*ListShelvesRequest)(nil),  // 0: bookstore.v2.ListShelvesRequest
	(*ListShelvesResponse)(nil), // 1: bookstore.v2.ListShelvesResponse
	(*CreateShelfRequest)(nil),  // 2: bookstore.v2.CreateShelfRequest
	(*CreateShelfResponse)(nil), // 3: bookstore.v2.CreateShelfResponse
	(*GetShelfRequest)(nil),     // 4: bookstore.v2.GetShelfRequest
	(*GetShelfResponse)(nil),    // 5: bookstore.v2.GetShelfResponse
}
var file_bookstore_v2_bookstore_proto_depIdxs = []int32{
	0, // 0: bookstore.v2.BookstoreService.ListShelves:input_type -> bookstore.v2.ListShelvesRequest
	2, // 1: bookstore.v2.BookstoreService.CreateShelf:input_type -> bookstore.v2.CreateShelfRequest
	4, // 2: bookstore.v2.BookstoreService.GetShelf:input_type -> bookstore.v2.GetShelfRequest
	1, // 3: bookstore.v2.BookstoreService.ListShelves:output_type -> bookstore.v2.ListShelvesResponse
	3, // 4: bookstore.v2.BookstoreService.CreateShelf:output_type -> bookstore.v2.CreateShelfResponse
	5, // 5: bookstore.v2.BookstoreService.GetShelf:output_type -> bookstore.v2.GetShelfResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bookstore_v2_bookstore_proto_init() }
func file_bookstore_v2_bookstore_proto_init() {
	if File_bookstore_v2_bookstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bookstore_v2_bookstore_proto_rawDesc), len(file_bookstore_v2_bookstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookstore_v2_bookstore_proto_goTypes,
		DependencyIndexes: file_bookstore_v2_bookstore_proto_depIdxs,
		MessageInfos:      file_bookstore_v2_bookstore_proto_msgTypes,
	}.Build()
	File_bookstore_v2_bookstore_proto = out.File
	file_bookstore_v2_bookstore_proto_goTypes = nil
	file_bookstore_v2_bookstore_proto_depIdxs = nil
}
