// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: bookstore/v2/bookstore.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookstoreService_ListShelves_FullMethodName = "/bookstore.v2.BookstoreService/ListShelves"
	BookstoreService_CreateShelf_FullMethodName = "/bookstore.v2.BookstoreService/CreateShelf"
	BookstoreService_GetShelf_FullMethodName    = "/bookstore.v2.BookstoreService/GetShelf"
)

// BookstoreServiceClient is the client API for BookstoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BookstoreService v2 intentionally shares its short name with
// bookstore.v1.BookstoreService. Without a group_override the generator
// would emit x-speakeasy-group: Bookstore for both versions, and the SDK
// would end up with two colliding receivers named sdk.Bookstore.ListShelves
// (one pointing at /shelves, one at /v2/shelves). Setting the
// service-level group_override below routes every RPC in this service
// into its own SDK namespace: sdk.BookstoreV2.ListShelves().
type BookstoreServiceClient interface {
	// Shares its RPC name with bookstore.v1.BookstoreService.ListShelves.
	// Disambiguated via the service-level group_override above.
	ListShelves(ctx context.Context, in *ListShelvesRequest, opts ...grpc.CallOption) (*ListShelvesResponse, error)
	// Demonstrates Operation.name_override — replaces the default
	// x-speakeasy-name-override (RPC method name) for this single method.
	// Rare in practice; use when one operation in a service needs a
	// different SDK method name from what the proto declares.
	CreateShelf(ctx context.Context, in *CreateShelfRequest, opts ...grpc.CallOption) (*CreateShelfResponse, error)
	// Demonstrates Operation.group_override — takes precedence over the
	// service-level group_override for this one method. Rarer still; use
	// only when a single RPC needs to live in a different SDK namespace
	// from the rest of its service.
	GetShelf(ctx context.Context, in *GetShelfRequest, opts ...grpc.CallOption) (*GetShelfResponse, error)
}

type bookstoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookstoreServiceClient(cc grpc.ClientConnInterface) BookstoreServiceClient {
	return &bookstoreServiceClient{cc}
}

func (c *bookstoreServiceClient) ListShelves(ctx context.Context, in *ListShelvesRequest, opts ...grpc.CallOption) (*ListShelvesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShelvesResponse)
	err := c.cc.Invoke(ctx, BookstoreService_ListShelves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreServiceClient) CreateShelf(ctx context.Context, in *CreateShelfRequest, opts ...grpc.CallOption) (*CreateShelfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShelfResponse)
	err := c.cc.Invoke(ctx, BookstoreService_CreateShelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreServiceClient) GetShelf(ctx context.Context, in *GetShelfRequest, opts ...grpc.CallOption) (*GetShelfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShelfResponse)
	err := c.cc.Invoke(ctx, BookstoreService_GetShelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookstoreServiceServer is the server API for BookstoreService service.
// All implementations must embed UnimplementedBookstoreServiceServer
// for forward compatibility.
//
// BookstoreService v2 intentionally shares its short name with
// bookstore.v1.BookstoreService. Without a group_override the generator
// would emit x-speakeasy-group: Bookstore for both versions, and the SDK
// would end up with two colliding receivers named sdk.Bookstore.ListShelves
// (one pointing at /shelves, one at /v2/shelves). Setting the
// service-level group_override below routes every RPC in this service
// into its own SDK namespace: sdk.BookstoreV2.ListShelves().
type BookstoreServiceServer interface {
	// Shares its RPC name with bookstore.v1.BookstoreService.ListShelves.
	// Disambiguated via the service-level group_override above.
	ListShelves(context.Context, *ListShelvesRequest) (*ListShelvesResponse, error)
	// Demonstrates Operation.name_override — replaces the default
	// x-speakeasy-name-override (RPC method name) for this single method.
	// Rare in practice; use when one operation in a service needs a
	// different SDK method name from what the proto declares.
	CreateShelf(context.Context, *CreateShelfRequest) (*CreateShelfResponse, error)
	// Demonstrates Operation.group_override — takes precedence over the
	// service-level group_override for this one method. Rarer still; use
	// only when a single RPC needs to live in a different SDK namespace
	// from the rest of its service.
	GetShelf(context.Context, *GetShelfRequest) (*GetShelfResponse, error)
	mustEmbedUnimplementedBookstoreServiceServer()
}

// UnimplementedBookstoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookstoreServiceServer struct{}

func (UnimplementedBookstoreServiceServer) ListShelves(context.Context, *ListShelvesRequest) (*ListShelvesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShelves not implemented")
}
func (UnimplementedBookstoreServiceServer) CreateShelf(context.Context, *CreateShelfRequest) (*CreateShelfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShelf not implemented")
}
func (UnimplementedBookstoreServiceServer) GetShelf(context.Context, *GetShelfRequest) (*GetShelfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShelf not implemented")
}
func (UnimplementedBookstoreServiceServer) mustEmbedUnimplementedBookstoreServiceServer() {}
func (UnimplementedBookstoreServiceServer) testEmbeddedByValue()                          {}

// UnsafeBookstoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookstoreServiceServer will
// result in compilation errors.
type UnsafeBookstoreServiceServer interface {
	mustEmbedUnimplementedBookstoreServiceServer()
}

func RegisterBookstoreServiceServer(s grpc.ServiceRegistrar, srv BookstoreServiceServer) {
	// If the following call panics, it indicates UnimplementedBookstoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookstoreService_ServiceDesc, srv)
}

func _BookstoreService_ListShelves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShelvesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServiceServer).ListShelves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookstoreService_ListShelves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServiceServer).ListShelves(ctx, req.(*ListShelvesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookstoreService_CreateShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServiceServer).CreateShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookstoreService_CreateShelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServiceServer).CreateShelf(ctx, req.(*CreateShelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookstoreService_GetShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServiceServer).GetShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookstoreService_GetShelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServiceServer).GetShelf(ctx, req.(*GetShelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookstoreService_ServiceDesc is the grpc.ServiceDesc for BookstoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookstoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bookstore.v2.BookstoreService",
	HandlerType: (*BookstoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListShelves",
			Handler:    _BookstoreService_ListShelves_Handler,
		},
		{
			MethodName: "CreateShelf",
			Handler:    _BookstoreService_CreateShelf_Handler,
		},
		{
			MethodName: "GetShelf",
			Handler:    _BookstoreService_GetShelf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bookstore/v2/bookstore.proto",
}
