// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: webhooks/v1/request.proto

package v1beta

import (
	_ "github.com/ductone/protoc-gen-apigw/apigw/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Webhook request body with stability and deprecation examples
type Body struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version contains the constant value "v1". Future versions of the Webhook body will use a different string.
	//
	// This value will match the "Webhook-Version" header.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Unique ID for this Webhook. Your receiver should only process this ID once.
	//
	// This value will match the "Webhook-Id" header.
	WebhookId string `protobuf:"bytes,2,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	// If your receiver returns HTTP Status Code 202 Accepted, it MUST send its response to this URL as a POST
	// message body.
	//
	// If your receiver returns any other status code, it is expected to not use the callback url.
	//
	// This value will match the "Webhook-Callback-Url" header.
	CallbackUrl string `protobuf:"bytes,3,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	// The type of event that triggered this Webhook.
	//
	// This value will match the "Webhook-Event" header.
	//
	// The value will be one of:
	// - "webhooks.v1.PayloadTest"
	// - "webhooks.v1.PayloadPolicyApprovalStep"
	// - "webhooks.v1.PayloadPolicyPostAction"
	// - "webhooks.v1.PayloadProvisionStep"
	Event string `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	// The Payload of the webhook.
	// The payload will be different depending on the event type.
	//
	// The @type will be one of:
	// - "type.googleapis.com/webhooks.v1.PayloadTest"
	// - "type.googleapis.com/webhooks.v1.PayloadPolicyApprovalStep"
	// - "type.googleapis.com/webhooks.v1.PayloadPolicyPostAction"
	// - "type.googleapis.com/webhooks.v1.PayloadProvisionStep"
	//
	// And map to the associated payload message type.
	Payload       *anypb.Any `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Body) Reset() {
	*x = Body{}
	mi := &file_webhooks_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Body) ProtoMessage() {}

func (x *Body) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Body.ProtoReflect.Descriptor instead.
func (*Body) Descriptor() ([]byte, []int) {
	return file_webhooks_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *Body) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Body) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *Body) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *Body) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Body) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PayloadTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadTest) Reset() {
	*x = PayloadTest{}
	mi := &file_webhooks_v1_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadTest) ProtoMessage() {}

func (x *PayloadTest) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_v1_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadTest.ProtoReflect.Descriptor instead.
func (*PayloadTest) Descriptor() ([]byte, []int) {
	return file_webhooks_v1_request_proto_rawDescGZIP(), []int{1}
}

// Task view with field-level stability annotations
type TaskView struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Deprecated: Marked as deprecated in webhooks/v1/request.proto.
	OtherField    string `protobuf:"bytes,2,opt,name=other_field,json=search[decoded],proto3" json:"other_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskView) Reset() {
	*x = TaskView{}
	mi := &file_webhooks_v1_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskView) ProtoMessage() {}

func (x *TaskView) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_v1_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskView.ProtoReflect.Descriptor instead.
func (*TaskView) Descriptor() ([]byte, []int) {
	return file_webhooks_v1_request_proto_rawDescGZIP(), []int{2}
}

func (x *TaskView) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// Deprecated: Marked as deprecated in webhooks/v1/request.proto.
func (x *TaskView) GetOtherField() string {
	if x != nil {
		return x.OtherField
	}
	return ""
}

type PayloadPolicyApprovalStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A view of the task, contains the serialized task and paths to objects referenced by the task
	TaskView *TaskView `protobuf:"bytes,1,opt,name=task_view,json=taskView,proto3" json:"task_view,omitempty"`
	// List of serialized related objects.
	Expanded      []*anypb.Any `protobuf:"bytes,2,rep,name=expanded,proto3" json:"expanded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadPolicyApprovalStep) Reset() {
	*x = PayloadPolicyApprovalStep{}
	mi := &file_webhooks_v1_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadPolicyApprovalStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadPolicyApprovalStep) ProtoMessage() {}

func (x *PayloadPolicyApprovalStep) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_v1_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadPolicyApprovalStep.ProtoReflect.Descriptor instead.
func (*PayloadPolicyApprovalStep) Descriptor() ([]byte, []int) {
	return file_webhooks_v1_request_proto_rawDescGZIP(), []int{3}
}

func (x *PayloadPolicyApprovalStep) GetTaskView() *TaskView {
	if x != nil {
		return x.TaskView
	}
	return nil
}

func (x *PayloadPolicyApprovalStep) GetExpanded() []*anypb.Any {
	if x != nil {
		return x.Expanded
	}
	return nil
}

type PayloadPolicyPostAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A view of the task, contains the serialized task and paths to objects referenced by the task
	TaskView *TaskView `protobuf:"bytes,1,opt,name=task_view,json=taskView,proto3" json:"task_view,omitempty"`
	// List of serialized related objects.
	Expanded      []*anypb.Any `protobuf:"bytes,2,rep,name=expanded,proto3" json:"expanded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadPolicyPostAction) Reset() {
	*x = PayloadPolicyPostAction{}
	mi := &file_webhooks_v1_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadPolicyPostAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadPolicyPostAction) ProtoMessage() {}

func (x *PayloadPolicyPostAction) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_v1_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadPolicyPostAction.ProtoReflect.Descriptor instead.
func (*PayloadPolicyPostAction) Descriptor() ([]byte, []int) {
	return file_webhooks_v1_request_proto_rawDescGZIP(), []int{4}
}

func (x *PayloadPolicyPostAction) GetTaskView() *TaskView {
	if x != nil {
		return x.TaskView
	}
	return nil
}

func (x *PayloadPolicyPostAction) GetExpanded() []*anypb.Any {
	if x != nil {
		return x.Expanded
	}
	return nil
}

type PayloadProvisionStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A view of the task, contains the serialized task and paths to objects referenced by the task
	TaskView *TaskView `protobuf:"bytes,1,opt,name=task_view,json=taskView,proto3" json:"task_view,omitempty"`
	// List of serialized related objects.
	Expanded      []*anypb.Any `protobuf:"bytes,2,rep,name=expanded,proto3" json:"expanded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadProvisionStep) Reset() {
	*x = PayloadProvisionStep{}
	mi := &file_webhooks_v1_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadProvisionStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadProvisionStep) ProtoMessage() {}

func (x *PayloadProvisionStep) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_v1_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadProvisionStep.ProtoReflect.Descriptor instead.
func (*PayloadProvisionStep) Descriptor() ([]byte, []int) {
	return file_webhooks_v1_request_proto_rawDescGZIP(), []int{5}
}

func (x *PayloadProvisionStep) GetTaskView() *TaskView {
	if x != nil {
		return x.TaskView
	}
	return nil
}

func (x *PayloadProvisionStep) GetExpanded() []*anypb.Any {
	if x != nil {
		return x.Expanded
	}
	return nil
}

var File_webhooks_v1_request_proto protoreflect.FileDescriptor

const file_webhooks_v1_request_proto_rawDesc = "" +
	"\n" +
	"\x19webhooks/v1/request.proto\x12\vwebhooks.v1\x1a\x14apigw/v1/apigw.proto\x1a\x19google/protobuf/any.proto\"\xc6\x01\n" +
	"\x04Body\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x02 \x01(\tR\twebhookId\x12!\n" +
	"\fcallback_url\x18\x03 \x01(\tR\vcallbackUrl\x12\x14\n" +
	"\x05event\x18\x04 \x01(\tR\x05event\x12.\n" +
	"\apayload\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\apayload:\x1c\xaa\xde\x03\x18\n" +
	"\x16\x18\x01\"\x12webhookNameExample\"\x17\n" +
	"\vPayloadTest:\b\xaa\xde\x03\x04\n" +
	"\x02\x18\x01\"a\n" +
	"\bTaskView\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12<\n" +
	"\vother_field\x18\x02 \x01(\tB\x16\xa2\xde\x03\x10\n" +
	"\x0e\"\f\n" +
	"\n" +
	"2025-09-30\x18\x01R\x0fsearch[decoded]\"\x8b\x01\n" +
	"\x19PayloadPolicyApprovalStep\x122\n" +
	"\ttask_view\x18\x01 \x01(\v2\x15.webhooks.v1.TaskViewR\btaskView\x120\n" +
	"\bexpanded\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\bexpanded:\b\xaa\xde\x03\x04\n" +
	"\x02\x18\x01\"\x89\x01\n" +
	"\x17PayloadPolicyPostAction\x122\n" +
	"\ttask_view\x18\x01 \x01(\v2\x15.webhooks.v1.TaskViewR\btaskView\x120\n" +
	"\bexpanded\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\bexpanded:\b\xaa\xde\x03\x04\n" +
	"\x02\x18\x01\"\x86\x01\n" +
	"\x14PayloadProvisionStep\x122\n" +
	"\ttask_view\x18\x01 \x01(\v2\x15.webhooks.v1.TaskViewR\btaskView\x120\n" +
	"\bexpanded\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\bexpanded:\b\xaa\xde\x03\x04\n" +
	"\x02\x18\x01B1Z/gitlab.com/ductone/c1/pkg/pb/c1/webhooks/v1betab\x06proto3"

var (
	file_webhooks_v1_request_proto_rawDescOnce sync.Once
	file_webhooks_v1_request_proto_rawDescData []byte
)

func file_webhooks_v1_request_proto_rawDescGZIP() []byte {
	file_webhooks_v1_request_proto_rawDescOnce.Do(func() {
		file_webhooks_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webhooks_v1_request_proto_rawDesc), len(file_webhooks_v1_request_proto_rawDesc)))
	})
	return file_webhooks_v1_request_proto_rawDescData
}

var file_webhooks_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_webhooks_v1_request_proto_goTypes = []any{
	(*Body)(nil),                      // 0: webhooks.v1.Body
	(*PayloadTest)(nil),               // 1: webhooks.v1.PayloadTest
	(*TaskView)(nil),                  // 2: webhooks.v1.TaskView
	(*PayloadPolicyApprovalStep)(nil), // 3: webhooks.v1.PayloadPolicyApprovalStep
	(*PayloadPolicyPostAction)(nil),   // 4: webhooks.v1.PayloadPolicyPostAction
	(*PayloadProvisionStep)(nil),      // 5: webhooks.v1.PayloadProvisionStep
	(*anypb.Any)(nil),                 // 6: google.protobuf.Any
}
var file_webhooks_v1_request_proto_depIdxs = []int32{
	6, // 0: webhooks.v1.Body.payload:type_name -> google.protobuf.Any
	2, // 1: webhooks.v1.PayloadPolicyApprovalStep.task_view:type_name -> webhooks.v1.TaskView
	6, // 2: webhooks.v1.PayloadPolicyApprovalStep.expanded:type_name -> google.protobuf.Any
	2, // 3: webhooks.v1.PayloadPolicyPostAction.task_view:type_name -> webhooks.v1.TaskView
	6, // 4: webhooks.v1.PayloadPolicyPostAction.expanded:type_name -> google.protobuf.Any
	2, // 5: webhooks.v1.PayloadProvisionStep.task_view:type_name -> webhooks.v1.TaskView
	6, // 6: webhooks.v1.PayloadProvisionStep.expanded:type_name -> google.protobuf.Any
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_webhooks_v1_request_proto_init() }
func file_webhooks_v1_request_proto_init() {
	if File_webhooks_v1_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webhooks_v1_request_proto_rawDesc), len(file_webhooks_v1_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webhooks_v1_request_proto_goTypes,
		DependencyIndexes: file_webhooks_v1_request_proto_depIdxs,
		MessageInfos:      file_webhooks_v1_request_proto_msgTypes,
	}.Build()
	File_webhooks_v1_request_proto = out.File
	file_webhooks_v1_request_proto_goTypes = nil
	file_webhooks_v1_request_proto_depIdxs = nil
}
