---
components:
  schemas:
    webhooks.v1.PolicyStep:
      description: The PolicyStep message.
      properties:
        policyStepId:
          description: The policyStepId field.
          nullable: true
          readOnly: false
          type: string
      title: Policy Step
      type: object
      x-speakeasy-name-override: PolicyStep
    webhooks.v1.ResponsePolicyApprovalStep:
      description: |
        The ResponsePolicyApprovalStep message.

        This message contains a oneof named action. Only a single field of the following list may be set at a time:
          - approve
          - deny
          - reassign
          - replacePolicy
      properties:
        approve:
          oneOf:
            - $ref: '#/components/schemas/webhooks.v1.ResponsePolicyApprovalStep.ResponsePolicyApprovalStepApprove'
            - type: "null"
        deny:
          oneOf:
            - $ref: '#/components/schemas/webhooks.v1.ResponsePolicyApprovalStep.ResponsePolicyApprovalStepDeny'
            - type: "null"
        reassign:
          oneOf:
            - $ref: '#/components/schemas/webhooks.v1.ResponsePolicyApprovalStep.ResponsePolicyApprovalStepReassign'
            - type: "null"
        replacePolicy:
          oneOf:
            - $ref: '#/components/schemas/webhooks.v1.ResponsePolicyApprovalStep.ResponsePolicyApprovalReplacePolicy'
            - type: "null"
        version:
          description: |-
            version contains the constant value "v1". Future versions of the Webhook Response
             will use a different string.
          nullable: true
          readOnly: false
          type: string
      title: Response Policy Approval Step
      type: object
      x-speakeasy-include: true
      x-speakeasy-name-override: ResponsePolicyApprovalStep
    webhooks.v1.ResponsePolicyApprovalStep.ResponsePolicyApprovalReplacePolicy:
      description: The ResponsePolicyApprovalReplacePolicy message.
      properties:
        comment:
          description: The comment field.
          nullable: true
          readOnly: false
          type: string
        policySteps:
          description: The policySteps field.
          items:
            $ref: '#/components/schemas/webhooks.v1.PolicyStep'
          nullable: true
          readOnly: false
          type: array
      title: Response Policy Approval Replace Policy
      type: object
      x-speakeasy-name-override: ResponsePolicyApprovalReplacePolicy
    webhooks.v1.ResponsePolicyApprovalStep.ResponsePolicyApprovalStepApprove:
      description: The ResponsePolicyApprovalStepApprove message.
      properties:
        comment:
          description: optional comment
          nullable: true
          readOnly: false
          type: string
      title: Response Policy Approval Step Approve
      type: object
      x-speakeasy-name-override: ResponsePolicyApprovalStepApprove
    webhooks.v1.ResponsePolicyApprovalStep.ResponsePolicyApprovalStepDeny:
      description: The ResponsePolicyApprovalStepDeny message.
      properties:
        comment:
          description: optional comment
          nullable: true
          readOnly: false
          type: string
      title: Response Policy Approval Step Deny
      type: object
      x-speakeasy-name-override: ResponsePolicyApprovalStepDeny
    webhooks.v1.ResponsePolicyApprovalStep.ResponsePolicyApprovalStepReassign:
      description: The ResponsePolicyApprovalStepReassign message.
      properties:
        comment:
          description: optional comment
          nullable: true
          readOnly: false
          type: string
        newStepUserIds:
          description: The newStepUserIds field.
          items:
            type: string
          nullable: true
          readOnly: false
          type: array
      title: Response Policy Approval Step Reassign
      type: object
      x-speakeasy-name-override: ResponsePolicyApprovalStepReassign
    webhooks.v1.ResponsePolicyPostAction:
      description: The ResponsePolicyPostAction message.
      properties:
        version:
          description: |-
            version contains the constant value "v1". Future versions of the Webhook Response
             will use a different string.
          nullable: true
          readOnly: false
          type: string
      title: Response Policy Post Action
      type: object
      x-speakeasy-include: true
      x-speakeasy-name-override: ResponsePolicyPostAction
    webhooks.v1.ResponseProvisionStep:
      description: |
        The ResponseProvisionStep message.

        This message contains a oneof named outcome. Only a single field of the following list may be set at a time:
          - complete
          - errored
      properties:
        complete:
          oneOf:
            - $ref: '#/components/schemas/webhooks.v1.ResponseProvisionStep.ResponseProvisionStepComplete'
            - type: "null"
        errored:
          oneOf:
            - $ref: '#/components/schemas/webhooks.v1.ResponseProvisionStep.ResponseProvisionStepErrored'
            - type: "null"
        version:
          description: |-
            version contains the constant value "v1". Future versions of the Webhook Response
             will use a different string.
          nullable: true
          readOnly: false
          type: string
      title: Response Provision Step
      type: object
      x-speakeasy-include: true
      x-speakeasy-name-override: ResponseProvisionStep
    webhooks.v1.ResponseProvisionStep.ResponseProvisionStepComplete:
      description: The ResponseProvisionStepComplete message.
      properties:
        comment:
          description: optional comment
          nullable: true
          readOnly: false
          type: string
      title: Response Provision Step Complete
      type: object
      x-speakeasy-name-override: ResponseProvisionStepComplete
    webhooks.v1.ResponseProvisionStep.ResponseProvisionStepErrored:
      description: The ResponseProvisionStepErrored message.
      properties:
        comment:
          description: optional comment
          nullable: true
          readOnly: false
          type: string
      title: Response Provision Step Errored
      type: object
      x-speakeasy-name-override: ResponseProvisionStepErrored
    webhooks.v1.ResponseTest:
      description: The ResponseTest message.
      properties:
        version:
          description: |-
            version contains the constant value "v1". Future versions of the Webhook Response
             will use a different string.
          nullable: true
          readOnly: false
          type: string
      title: Response Test
      type: object
      x-speakeasy-include: true
      x-speakeasy-name-override: ResponseTest
info:
  description: |
    This is an auto-generated Definitions for webhooks.v1.
  title: Definitions For webhooks.v1
  version: 0.0.1
openapi: 3.1.0
