// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tfcustomize/v1/tfcustomize.proto

package v1

import (
	_ "github.com/ductone/protoc-gen-apigw/apigw/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tfcustomize_v1_tfcustomize_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_tfcustomize_v1_tfcustomize_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_tfcustomize_v1_tfcustomize_proto_rawDescGZIP(), []int{0}
}

type GetThingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThingId       string                 `protobuf:"bytes,1,opt,name=thing_id,json=thingId,proto3" json:"thing_id,omitempty"`
	Flavor        string                 `protobuf:"bytes,2,opt,name=flavor,proto3" json:"flavor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThingRequest) Reset() {
	*x = GetThingRequest{}
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThingRequest) ProtoMessage() {}

func (x *GetThingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThingRequest.ProtoReflect.Descriptor instead.
func (*GetThingRequest) Descriptor() ([]byte, []int) {
	return file_tfcustomize_v1_tfcustomize_proto_rawDescGZIP(), []int{0}
}

func (x *GetThingRequest) GetThingId() string {
	if x != nil {
		return x.ThingId
	}
	return ""
}

func (x *GetThingRequest) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

type GetThingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thing         *Thing                 `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThingResponse) Reset() {
	*x = GetThingResponse{}
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThingResponse) ProtoMessage() {}

func (x *GetThingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThingResponse.ProtoReflect.Descriptor instead.
func (*GetThingResponse) Descriptor() ([]byte, []int) {
	return file_tfcustomize_v1_tfcustomize_proto_rawDescGZIP(), []int{1}
}

func (x *GetThingResponse) GetThing() *Thing {
	if x != nil {
		return x.Thing
	}
	return nil
}

type ListThingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThingsRequest) Reset() {
	*x = ListThingsRequest{}
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThingsRequest) ProtoMessage() {}

func (x *ListThingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThingsRequest.ProtoReflect.Descriptor instead.
func (*ListThingsRequest) Descriptor() ([]byte, []int) {
	return file_tfcustomize_v1_tfcustomize_proto_rawDescGZIP(), []int{2}
}

type ListThingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Things        []*Thing               `protobuf:"bytes,1,rep,name=things,proto3" json:"things,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThingsResponse) Reset() {
	*x = ListThingsResponse{}
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThingsResponse) ProtoMessage() {}

func (x *ListThingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThingsResponse.ProtoReflect.Descriptor instead.
func (*ListThingsResponse) Descriptor() ([]byte, []int) {
	return file_tfcustomize_v1_tfcustomize_proto_rawDescGZIP(), []int{3}
}

func (x *ListThingsResponse) GetThings() []*Thing {
	if x != nil {
		return x.Things
	}
	return nil
}

type CreateThingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thing         *Thing                 `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateThingRequest) Reset() {
	*x = CreateThingRequest{}
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThingRequest) ProtoMessage() {}

func (x *CreateThingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThingRequest.ProtoReflect.Descriptor instead.
func (*CreateThingRequest) Descriptor() ([]byte, []int) {
	return file_tfcustomize_v1_tfcustomize_proto_rawDescGZIP(), []int{4}
}

func (x *CreateThingRequest) GetThing() *Thing {
	if x != nil {
		return x.Thing
	}
	return nil
}

type CreateThingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thing         *Thing                 `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateThingResponse) Reset() {
	*x = CreateThingResponse{}
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThingResponse) ProtoMessage() {}

func (x *CreateThingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThingResponse.ProtoReflect.Descriptor instead.
func (*CreateThingResponse) Descriptor() ([]byte, []int) {
	return file_tfcustomize_v1_tfcustomize_proto_rawDescGZIP(), []int{5}
}

func (x *CreateThingResponse) GetThing() *Thing {
	if x != nil {
		return x.Thing
	}
	return nil
}

// A thing resource.
type Thing struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags   []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Labels map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A singular message field: the override belongs to this property, not to
	// the shared Thing component. The typed stability annotation exercises the
	// nullable-$ref wrapper path, which used to drop a field's extension bag.
	Child     *Thing                 `protobuf:"bytes,4,opt,name=child,proto3" json:"child,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status    Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=tfcustomize.v1.Status" json:"status,omitempty"`
	// The property name contains a "/" so the emitted pointer has to escape the
	// reference token.
	OddName string `protobuf:"bytes,7,opt,name=odd_name,json=odd/name,proto3" json:"odd_name,omitempty"`
	// The JSON Pointer escape hatch, on a field: the destination node need not
	// be reachable by any enumerated target.
	Escaped string `protobuf:"bytes,8,opt,name=escaped,proto3" json:"escaped,omitempty"`
	// Types that are valid to be assigned to Policy:
	//
	//	*Thing_ManualPolicy
	//	*Thing_MultiStepPolicy
	Policy        isThing_Policy `protobuf_oneof:"policy"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Thing) Reset() {
	*x = Thing{}
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thing) ProtoMessage() {}

func (x *Thing) ProtoReflect() protoreflect.Message {
	mi := &file_tfcustomize_v1_tfcustomize_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thing.ProtoReflect.Descriptor instead.
func (*Thing) Descriptor() ([]byte, []int) {
	return file_tfcustomize_v1_tfcustomize_proto_rawDescGZIP(), []int{6}
}

func (x *Thing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Thing) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Thing) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Thing) GetChild() *Thing {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *Thing) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Thing) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Thing) GetOddName() string {
	if x != nil {
		return x.OddName
	}
	return ""
}

func (x *Thing) GetEscaped() string {
	if x != nil {
		return x.Escaped
	}
	return ""
}

func (x *Thing) GetPolicy() isThing_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Thing) GetManualPolicy() string {
	if x != nil {
		if x, ok := x.Policy.(*Thing_ManualPolicy); ok {
			return x.ManualPolicy
		}
	}
	return ""
}

func (x *Thing) GetMultiStepPolicy() string {
	if x != nil {
		if x, ok := x.Policy.(*Thing_MultiStepPolicy); ok {
			return x.MultiStepPolicy
		}
	}
	return ""
}

type isThing_Policy interface {
	isThing_Policy()
}

type Thing_ManualPolicy struct {
	ManualPolicy string `protobuf:"bytes,9,opt,name=manual_policy,json=manualPolicy,proto3,oneof"`
}

type Thing_MultiStepPolicy struct {
	MultiStepPolicy string `protobuf:"bytes,10,opt,name=multi_step_policy,json=multiStepPolicy,proto3,oneof"`
}

func (*Thing_ManualPolicy) isThing_Policy() {}

func (*Thing_MultiStepPolicy) isThing_Policy() {}

var File_tfcustomize_v1_tfcustomize_proto protoreflect.FileDescriptor

const file_tfcustomize_v1_tfcustomize_proto_rawDesc = "" +
	"\n" +
	" tfcustomize/v1/tfcustomize.proto\x12\x0etfcustomize.v1\x1a\x14apigw/v1/apigw.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\x0fGetThingRequest\x12e\n" +
	"\bthing_id\x18\x01 \x01(\tBJ\xa2\xde\x03F\n" +
	"D\b\x012\x1b\n" +
	"\x11x-speakeasy-match\x12\x04\"id\"\x18\x022#\n" +
	"\x1ax-speakeasy-param-readonly\x12\x05falseR\athingId\x12?\n" +
	"\x06flavor\x18\x02 \x01(\tB'\xa2\xde\x03#\n" +
	"!2\x1f\n" +
	"\x11x-speakeasy-match\x12\b\"flavor\"\x18\x02R\x06flavor\"?\n" +
	"\x10GetThingResponse\x12+\n" +
	"\x05thing\x18\x01 \x01(\v2\x15.tfcustomize.v1.ThingR\x05thing\"\x13\n" +
	"\x11ListThingsRequest\"C\n" +
	"\x12ListThingsResponse\x12-\n" +
	"\x06things\x18\x01 \x03(\v2\x15.tfcustomize.v1.ThingR\x06things\"A\n" +
	"\x12CreateThingRequest\x12+\n" +
	"\x05thing\x18\x01 \x01(\v2\x15.tfcustomize.v1.ThingR\x05thing\"B\n" +
	"\x13CreateThingResponse\x12+\n" +
	"\x05thing\x18\x01 \x01(\v2\x15.tfcustomize.v1.ThingR\x05thing\"\xb9\r\n" +
	"\x05Thing\x12\x96\x01\n" +
	"\x02id\x18\x01 \x01(\tB\x85\x01\xa2\xde\x03\x80\x01\n" +
	"~\x18\x042\"\n" +
	"\x1ax-speakeasy-param-readonly\x12\x04true2/\n" +
	"\x19x-speakeasy-name-override\x12\x12\"thing_identifier\":%\x1a#{\"default\":\"unknown\",\"minLength\":1}R\x02id\x12z\n" +
	"\x04tags\x18\x02 \x03(\tBf\xa2\xde\x03b\n" +
	"`2%\n" +
	"\x1bx-speakeasy-response-filter\x12\x04true\x18\x032%\n" +
	"\x1cx-speakeasy-terraform-ignore\x12\x05false:\x10\x1a\x0e{\"default\":[]}R\x04tags\x12g\n" +
	"\x06labels\x18\x03 \x03(\v2!.tfcustomize.v1.Thing.LabelsEntryB,\xa2\xde\x03(\n" +
	"&2$\n" +
	"\x19x-speakeasy-type-override\x12\x05\"any\"\x18\x04R\x06labels\x12a\n" +
	"\x05child\x18\x04 \x01(\v2\x15.tfcustomize.v1.ThingB4\xa2\xde\x030\n" +
	".\x18\x042*\n" +
	"\x19x-speakeasy-name-override\x12\r\"child_thing\"R\x05child\x12r\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB7\xa2\xde\x033\n" +
	"1\x18\x042#\n" +
	"\x1ax-speakeasy-param-computed\x12\x05false:\b\"\x06formatR\tcreatedAt\x12\x86\x01\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.tfcustomize.v1.StatusBV\xa2\xde\x03R\n" +
	"P2(\n" +
	"\x1ax-speakeasy-unknown-values\x12\n" +
	"\"disallow\"2$\n" +
	"\x17x-speakeasy-enum-format\x12\a\"union\"(\x02R\x06status\x12O\n" +
	"\bodd_name\x18\a \x01(\tB3\xa2\xde\x03/\n" +
	"-2+\n" +
	"\x1fx-speakeasy-deprecation-message\x12\b\"use id\"R\bodd/name\x12\x9c\x02\n" +
	"\aescaped\x18\b \x01(\tB\x81\x02\xa2\xde\x03\xfc\x01\n" +
	"\xf9\x012s\n" +
	"\x10x-speakeasy-docs\x12 {\"go\":\"Escaped pointer target.\"}\x18\t\";/components/schemas/tfcustomize.v1.Thing/properties/escaped2\x81\x01\n" +
	"\x18x-speakeasy-param-source\x12&{\"kind\":\"config\",\"path\":[\"a/b\",\"c~d\"]}\x18\t\";/components/schemas/tfcustomize.v1.Thing/properties/escapedR\aescaped\x12S\n" +
	"\rmanual_policy\x18\t \x01(\tB,\xa2\xde\x03(\n" +
	"&2$\n" +
	"\x1bx-speakeasy-param-force-new\x12\x05falseH\x00R\fmanualPolicy\x12,\n" +
	"\x11multi_step_policy\x18\n" +
	" \x01(\tH\x00R\x0fmultiStepPolicy\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x99\x03\xaa\xde\x03\x94\x03\n" +
	"\x91\x03\n" +
	"\a\x12\x05Thing29\n" +
	"\x1ex-speakeasy-entity-description\x12\x17\"A **thing** resource.\"2=\n" +
	"\x0ex-future-thing\x12+{\"nested\":{\"list\":[1,2.50,null,false,\"x\"]}}2 \n" +
	"\fx-future-int\x12\x1090071992547409932\x18\n" +
	"\x10x-future-decimal\x12\x041.502\x1b\n" +
	"\x15x-future-empty-string\x12\x02\"\"2\x1a\n" +
	"\x14x-future-empty-array\x12\x02[]2\x1b\n" +
	"\x15x-future-empty-object\x12\x02{}2\x17\n" +
	"\x0ex-future-false\x12\x05false2\x15\n" +
	"\rx-future-null\x12\x04null2*\n" +
	"\x12x-future-multiline\x12\x14\"line one\\nline two\":\x15\x1a\x13{\"required\":[\"id\"]}:\a\"\x05titleB\b\n" +
	"\x06policy*3\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x012\xd2\x06\n" +
	"\x10CustomizeService\x12\x9e\x02\n" +
	"\bGetThing\x12\x1f.tfcustomize.v1.GetThingRequest\x1a .tfcustomize.v1.GetThingResponse\"\xce\x01\x9a\xde\x03\xc9\x01\n" +
	"\xc6\x01\n" +
	"\x03GET\x12\x12/things/{thing_id}\x1a\x10\n" +
	"\x06flavor\x12\x06flavorB\t\b\x02\x12\x05Thingz-\n" +
	" x-speakeasy-entity-missing-codes\x12\t[403,410]z_\n" +
	"\x1cx-speakeasy-entity-operation\x12?{\"terraform-datasource\":null,\"terraform-resource\":\"Thing#read\"}\x12\xbd\x01\n" +
	"\n" +
	"ListThings\x12!.tfcustomize.v1.ListThingsRequest\x1a\".tfcustomize.v1.ListThingsResponse\"h\x9a\xde\x03d\n" +
	"b\n" +
	"\x03GET\x12\a/thingsB\f\b\x02\x12\x06Things(\x02zD\n" +
	"\x16x-speakeasy-pagination\x12*{\"type\":\"cursor\",\"inputs\":[],\"outputs\":{}}\x12\xe6\x01\n" +
	"\vCreateThing\x12\".tfcustomize.v1.CreateThingRequest\x1a#.tfcustomize.v1.CreateThingResponse\"\x8d\x01\x9a\xde\x03\x88\x01\n" +
	"\x85\x01\n" +
	"\x04POST\x12\a/thingsB\t\b\x01\x12\x05ThingzL\n" +
	"\x13x-speakeasy-polling\x125[{\"name\":\"wait\",\"intervalSeconds\":10,\"limitCount\":5}]z\x1b\n" +
	"\x12x-speakeasy-ignore\x12\x05false\x1at\x92\xde\x03p\n" +
	"n\b\x04*F\n" +
	"\x13x-speakeasy-globals\x12/{\"parameters\":[{\"name\":\"tenant\",\"in\":\"query\"}]}*\"\n" +
	"\x1dx-speakeasy-max-method-params\x12\x017Bn\xb2\xde\x03.\n" +
	",\n" +
	"\x1bx-speakeasy-model-namespace\x12\r\"tfcustomize\"Z:github.com/ductone/protoc-gen-apigw/example/tfcustomize/v1b\x06proto3"

var (
	file_tfcustomize_v1_tfcustomize_proto_rawDescOnce sync.Once
	file_tfcustomize_v1_tfcustomize_proto_rawDescData []byte
)

func file_tfcustomize_v1_tfcustomize_proto_rawDescGZIP() []byte {
	file_tfcustomize_v1_tfcustomize_proto_rawDescOnce.Do(func() {
		file_tfcustomize_v1_tfcustomize_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tfcustomize_v1_tfcustomize_proto_rawDesc), len(file_tfcustomize_v1_tfcustomize_proto_rawDesc)))
	})
	return file_tfcustomize_v1_tfcustomize_proto_rawDescData
}

var file_tfcustomize_v1_tfcustomize_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tfcustomize_v1_tfcustomize_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tfcustomize_v1_tfcustomize_proto_goTypes = []any{
	(Status)(0),                   // 0: tfcustomize.v1.Status
	(*GetThingRequest)(nil),       // 1: tfcustomize.v1.GetThingRequest
	(*GetThingResponse)(nil),      // 2: tfcustomize.v1.GetThingResponse
	(*ListThingsRequest)(nil),     // 3: tfcustomize.v1.ListThingsRequest
	(*ListThingsResponse)(nil),    // 4: tfcustomize.v1.ListThingsResponse
	(*CreateThingRequest)(nil),    // 5: tfcustomize.v1.CreateThingRequest
	(*CreateThingResponse)(nil),   // 6: tfcustomize.v1.CreateThingResponse
	(*Thing)(nil),                 // 7: tfcustomize.v1.Thing
	nil,                           // 8: tfcustomize.v1.Thing.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_tfcustomize_v1_tfcustomize_proto_depIdxs = []int32{
	7,  // 0: tfcustomize.v1.GetThingResponse.thing:type_name -> tfcustomize.v1.Thing
	7,  // 1: tfcustomize.v1.ListThingsResponse.things:type_name -> tfcustomize.v1.Thing
	7,  // 2: tfcustomize.v1.CreateThingRequest.thing:type_name -> tfcustomize.v1.Thing
	7,  // 3: tfcustomize.v1.CreateThingResponse.thing:type_name -> tfcustomize.v1.Thing
	8,  // 4: tfcustomize.v1.Thing.labels:type_name -> tfcustomize.v1.Thing.LabelsEntry
	7,  // 5: tfcustomize.v1.Thing.child:type_name -> tfcustomize.v1.Thing
	9,  // 6: tfcustomize.v1.Thing.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: tfcustomize.v1.Thing.status:type_name -> tfcustomize.v1.Status
	1,  // 8: tfcustomize.v1.CustomizeService.GetThing:input_type -> tfcustomize.v1.GetThingRequest
	3,  // 9: tfcustomize.v1.CustomizeService.ListThings:input_type -> tfcustomize.v1.ListThingsRequest
	5,  // 10: tfcustomize.v1.CustomizeService.CreateThing:input_type -> tfcustomize.v1.CreateThingRequest
	2,  // 11: tfcustomize.v1.CustomizeService.GetThing:output_type -> tfcustomize.v1.GetThingResponse
	4,  // 12: tfcustomize.v1.CustomizeService.ListThings:output_type -> tfcustomize.v1.ListThingsResponse
	6,  // 13: tfcustomize.v1.CustomizeService.CreateThing:output_type -> tfcustomize.v1.CreateThingResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_tfcustomize_v1_tfcustomize_proto_init() }
func file_tfcustomize_v1_tfcustomize_proto_init() {
	if File_tfcustomize_v1_tfcustomize_proto != nil {
		return
	}
	file_tfcustomize_v1_tfcustomize_proto_msgTypes[6].OneofWrappers = []any{
		(*Thing_ManualPolicy)(nil),
		(*Thing_MultiStepPolicy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tfcustomize_v1_tfcustomize_proto_rawDesc), len(file_tfcustomize_v1_tfcustomize_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tfcustomize_v1_tfcustomize_proto_goTypes,
		DependencyIndexes: file_tfcustomize_v1_tfcustomize_proto_depIdxs,
		EnumInfos:         file_tfcustomize_v1_tfcustomize_proto_enumTypes,
		MessageInfos:      file_tfcustomize_v1_tfcustomize_proto_msgTypes,
	}.Build()
	File_tfcustomize_v1_tfcustomize_proto = out.File
	file_tfcustomize_v1_tfcustomize_proto_goTypes = nil
	file_tfcustomize_v1_tfcustomize_proto_depIdxs = nil
}
