// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: tfcustomize/v1/tfcustomize.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomizeService_GetThing_FullMethodName    = "/tfcustomize.v1.CustomizeService/GetThing"
	CustomizeService_ListThings_FullMethodName  = "/tfcustomize.v1.CustomizeService/ListThings"
	CustomizeService_CreateThing_FullMethodName = "/tfcustomize.v1.CustomizeService/CreateThing"
)

// CustomizeServiceClient is the client API for CustomizeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CustomizeService exercises every documented annotation destination the
// transport supports: field schemas (scalar, enum, repeated, map, singular
// message, well-known type, oneof member), parameter objects as distinct from
// parameter schemas, array items, map values, message schemas, operations,
// request and response schemas, the document root and the JSON Pointer escape
// hatch.
//
// It is a fixture: the values are chosen to exercise transport, not to
// describe a real API, and nothing here is asserted to be honored by any
// particular Speakeasy release.
type CustomizeServiceClient interface {
	// A read operation that also carries the value-shape matrix.
	GetThing(ctx context.Context, in *GetThingRequest, opts ...grpc.CallOption) (*GetThingResponse, error)
	ListThings(ctx context.Context, in *ListThingsRequest, opts ...grpc.CallOption) (*ListThingsResponse, error)
	CreateThing(ctx context.Context, in *CreateThingRequest, opts ...grpc.CallOption) (*CreateThingResponse, error)
}

type customizeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomizeServiceClient(cc grpc.ClientConnInterface) CustomizeServiceClient {
	return &customizeServiceClient{cc}
}

func (c *customizeServiceClient) GetThing(ctx context.Context, in *GetThingRequest, opts ...grpc.CallOption) (*GetThingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThingResponse)
	err := c.cc.Invoke(ctx, CustomizeService_GetThing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customizeServiceClient) ListThings(ctx context.Context, in *ListThingsRequest, opts ...grpc.CallOption) (*ListThingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListThingsResponse)
	err := c.cc.Invoke(ctx, CustomizeService_ListThings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customizeServiceClient) CreateThing(ctx context.Context, in *CreateThingRequest, opts ...grpc.CallOption) (*CreateThingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateThingResponse)
	err := c.cc.Invoke(ctx, CustomizeService_CreateThing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomizeServiceServer is the server API for CustomizeService service.
// All implementations must embed UnimplementedCustomizeServiceServer
// for forward compatibility.
//
// CustomizeService exercises every documented annotation destination the
// transport supports: field schemas (scalar, enum, repeated, map, singular
// message, well-known type, oneof member), parameter objects as distinct from
// parameter schemas, array items, map values, message schemas, operations,
// request and response schemas, the document root and the JSON Pointer escape
// hatch.
//
// It is a fixture: the values are chosen to exercise transport, not to
// describe a real API, and nothing here is asserted to be honored by any
// particular Speakeasy release.
type CustomizeServiceServer interface {
	// A read operation that also carries the value-shape matrix.
	GetThing(context.Context, *GetThingRequest) (*GetThingResponse, error)
	ListThings(context.Context, *ListThingsRequest) (*ListThingsResponse, error)
	CreateThing(context.Context, *CreateThingRequest) (*CreateThingResponse, error)
	mustEmbedUnimplementedCustomizeServiceServer()
}

// UnimplementedCustomizeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomizeServiceServer struct{}

func (UnimplementedCustomizeServiceServer) GetThing(context.Context, *GetThingRequest) (*GetThingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThing not implemented")
}
func (UnimplementedCustomizeServiceServer) ListThings(context.Context, *ListThingsRequest) (*ListThingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListThings not implemented")
}
func (UnimplementedCustomizeServiceServer) CreateThing(context.Context, *CreateThingRequest) (*CreateThingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateThing not implemented")
}
func (UnimplementedCustomizeServiceServer) mustEmbedUnimplementedCustomizeServiceServer() {}
func (UnimplementedCustomizeServiceServer) testEmbeddedByValue()                          {}

// UnsafeCustomizeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomizeServiceServer will
// result in compilation errors.
type UnsafeCustomizeServiceServer interface {
	mustEmbedUnimplementedCustomizeServiceServer()
}

func RegisterCustomizeServiceServer(s grpc.ServiceRegistrar, srv CustomizeServiceServer) {
	// If the following call panics, it indicates UnimplementedCustomizeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomizeService_ServiceDesc, srv)
}

func _CustomizeService_GetThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomizeServiceServer).GetThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomizeService_GetThing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomizeServiceServer).GetThing(ctx, req.(*GetThingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomizeService_ListThings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListThingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomizeServiceServer).ListThings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomizeService_ListThings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomizeServiceServer).ListThings(ctx, req.(*ListThingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomizeService_CreateThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateThingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomizeServiceServer).CreateThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomizeService_CreateThing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomizeServiceServer).CreateThing(ctx, req.(*CreateThingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomizeService_ServiceDesc is the grpc.ServiceDesc for CustomizeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomizeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tfcustomize.v1.CustomizeService",
	HandlerType: (*CustomizeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThing",
			Handler:    _CustomizeService_GetThing_Handler,
		},
		{
			MethodName: "ListThings",
			Handler:    _CustomizeService_ListThings_Handler,
		},
		{
			MethodName: "CreateThing",
			Handler:    _CustomizeService_CreateThing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tfcustomize/v1/tfcustomize.proto",
}
